# Введение. Полносвязные слои. Функции активации (ноутбук)

> Начнем осваивать библиотеку `PyTorch`.

## План ноутбука

1. Установка `PyTorch`
1. Введение в `PyTorch`
1. Полносвязные слои и функции активации в `PyTorch`
1. Градиентный спуск своими руками
1. Подробнее про внутреннее устройство тензора

## Установка `PyTorch`

Мы будем использовать библиотеку для глубинного обучения `PyTorch`, ее можно не устанавливать, можно пользоваться сайтами [Kaggle](kaggle.com) и [Google Colab](colab.research.google.com/) для обучения в облаке (или с учителем?).

Чтобы установить `PyTorch` локально себе на компьютер нужно ответить на два вопроса - какая у вас операционная система и есть ли у вас дискретная видеокарта (GPU) и если есть, то какого производителя. В зависимости от ваших ответов мы получаем три варианта по операционной системе - Linux, Mac и Windows; три варианта по дискретной видеокарте - нет видеокарты (доступен только центральный процессор CPU), есть видеокарта от Nvidia или есть видеокарта от AMD (это производитель именно чипа, конечный вендор может быть другой, например, ASUS, MSI, Palit). Работа с PyTorch с видеокартой от AMD это экзотика, которая выходит за рамки нашего курса, поэтому рассмотрим только варианты *нет видеокарты*/*есть видеокарта от Nvidia*.


Выберите на [сайте](https://pytorch.org/get-started/locally/) подходящие вам варианты операционной системы/видеокарты и скопируйте команду для установки. Разберем подробно самые популярные варианты установки:

### Установка в Linux ([поддерживаемые дистрибутивы](https://pytorch.org/get-started/locally/#supported-linux-distributions))

На линуксе будет работать поддержка `PyTorch` в любой конфигурации, что у вас нет видеокарты, что есть от Nvidia, что от AMD.

Пререквизит для работы с видеокартой от Nvidia - нужно поставить CUDA, это инструмент от компании Nvidia, который позволяет ускорять вычисления на их же ГПУ. Чтобы поставить себе на машину все правильно воспользуйтесь этим [гайдом](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html) от Nvidia.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu` для тех, у кого нет видеокарты.

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116` для тех, у кого есть видеокарта (либо другой `--extra-index-url`, смотрите на сайте PyTorch, в зависимости от версии CUDA).

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch` для тех, у кого нет видеокарты.

`conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge` для тех, у кого есть видеокарта (либо немного другая команда, в зависимости от версии CUDA).

### Установка в Windows

На винде будет работать поддержка `PyTorch` только для видеокарт от Nvidia и без видеокарт вообще.

Пререквизит для работы с видеокартой от Nvidia - нужно поставить CUDA, это инструмент от компании Nvidia, который позволяет ускорять вычисления на их же ГПУ. Чтобы поставить себе на машину все правильно воспользуйтесь этим [гайдом](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html) от Nvidia.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu` для тех, у кого нет видеокарты.

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116` для тех, у кого есть видеокарта (либо другой `--extra-index-url`, смотрите на сайте PyTorch, в зависимости от версии CUDA).

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch` для тех, у кого нет видеокарты.

`conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge` для тех, у кого есть видеокарта (либо немного другая команда, в зависимости от версии CUDA).



### Установка на Mac

На маках есть пока что поддержка `PyTorch` только центрального процессора, чуть позже появится поддержка ускорения на чипах M1, M2, M1 Pro и так далее.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu`

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch`

In [ ]:
!nvidia-smi

Fri Oct 11 11:54:25 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Введение в `PyTorch`

### Тензоры

Тензоры — это специализированная структура данных, по сути это массивы и матрицы. Тензоры очень похожи на массивы в numpy, так что, если у вас хорошо с numpy, то разобраться в PyTorch тензорах будет очень просто. В PyTorch мы используем тензоры для кодирования входных и выходных данных модели, а также параметров модели.

In [1]:
import torch
import numpy as np

### Создание тензоров

Тензор можно создать напрямую из каких-то данных - нам подходят все списки с числами:

In [2]:
some_data = [1, 2, 3, 4]
some_tensor = torch.tensor(some_data)

some_tensor

tensor([1, 2, 3, 4])

In [3]:
some_data = [[1, 2], [3, 4], [5, 6]]
some_tensor = torch.tensor(some_data)

some_tensor

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [4]:
some_data = [[[1], [2]], [[3], [4]], [[5], [6]]]
some_tensor = torch.tensor(some_data)

some_tensor

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

На самом деле про "все" списки с числами - обман. Если у вашего списка есть какой-то уровень вложенности, то должны совпадать размерности у всех вложенных списков (подробнее про размерности поговорим позже):

In [5]:
some_other_data = [[1, 2], [3, 4], [5, 6, 7]]
some_other_tensor = torch.tensor(some_other_data)

some_other_tensor

ValueError: expected sequence of length 2 at dim 1 (got 3)

Также тензоры можно создавать из numpy массивов и наоборот:

In [6]:
some_numpy_array = np.array(some_data)

some_numpy_array

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [7]:
some_tensor_from_numpy = torch.from_numpy(some_numpy_array)

some_tensor_from_numpy

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

При этом если мы создаем тензор из numpy массива с помощью `torch.from_numpy`, то они делят между собой память, где лежат их данные и, соответственно, при изменении тензора меняется numpy массив и наоборот:

In [8]:
x = np.ones(10)
y = torch.from_numpy(x)

x, y

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64))

In [9]:
x += 1

x, y

(array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64))

In [10]:
x = torch.ones(10)
y = x.numpy()

x, y

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [11]:
x += 1

x, y

(tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=float32))

Можем создать тензор со случайными или константными значениями:

In [12]:
shape = (2, 3)

random_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
empty_tensor = torch.empty(shape)

random_tensor, ones_tensor, zeros_tensor, empty_tensor

(tensor([[0.1101, 0.1412, 0.5524],
         [0.1051, 0.1225, 0.6797]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1.6385e+22, 4.3342e-41, 7.7130e-10],
         [0.0000e+00, 4.4842e-44, 0.0000e+00]]))

In [13]:
torch.diag(torch.tensor([1, 2, 3]))

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

Теперь поговорим про размерности подробнее.

У тензора есть какой-то размер, какая форма. Первое с чем нужно определиться, какой **размерности** тензор - количество осей у него.

In [14]:
shape = (10)  # одна ось (вектор)

tensor = torch.rand(shape)

tensor

tensor([0.7579, 0.7765, 0.9386, 0.0668, 0.4880, 0.1414, 0.0691, 0.7946, 0.8423,
        0.6411])

In [15]:
shape = (2, 3)  # две оси (матрица)

tensor = torch.rand(shape)

tensor

tensor([[0.3568, 0.8172, 0.7891],
        [0.7221, 0.2696, 0.9371]])

In [16]:
shape = (3, 2, 3)  # три оси (и больше - тензор)

tensor = torch.rand(shape)

tensor

tensor([[[0.8896, 0.8535, 0.9793],
         [0.2872, 0.6683, 0.5938]],

        [[0.0284, 0.2067, 0.5752],
         [0.1611, 0.9662, 0.4000]],

        [[0.5927, 0.0445, 0.2863],
         [0.0191, 0.3821, 0.5447]]])

Тензор с размерностью 1 - это просто вектор, список чисел.

Тензор с размерностью 2 - это просто матрица, то есть список списков чисел.

Тензор с размерностью 3 и больше - это тензор, то есть список списков списков ... чисел.

Получить доступ к размеру уже созданного тензора - метод `.shape`:

In [17]:
some_data = [[[1], [2]], [[3], [4]], [[5], [6]]]
some_tensor = torch.tensor(some_data)

print(some_tensor)
print(some_tensor.shape)

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])
torch.Size([3, 2, 1])


In [18]:
torch.ones((3, 2, 1)).shape

torch.Size([3, 2, 1])

На первом семинаре по мо мы говорили про изображения, давайте сделаем тензор, который будет нам имитировать изображение - сделаем его размер `(c, h, w)`, где `h` и `w` это его высота и ширина, а `c` - число каналов в цветовом пространстве (в черно-белом 1, в RGB 3):

In [19]:
h = 9
w = 16
c = 3

shape = (c, h, w)

image_tensor = torch.rand(shape)

image_tensor

tensor([[[0.5659, 0.4856, 0.8741, 0.8532, 0.5410, 0.2716, 0.9388, 0.9431,
          0.2070, 0.2638, 0.1503, 0.0352, 0.0994, 0.4392, 0.2082, 0.1029],
         [0.6235, 0.8818, 0.1516, 0.7461, 0.6297, 0.5082, 0.6128, 0.6746,
          0.5185, 0.2862, 0.4001, 0.0150, 0.7387, 0.9917, 0.2264, 0.4910],
         [0.4452, 0.0088, 0.8830, 0.1260, 0.5734, 0.6298, 0.6813, 0.6440,
          0.2537, 0.4155, 0.2459, 0.1554, 0.7389, 0.4819, 0.9495, 0.7055],
         [0.5484, 0.0634, 0.5370, 0.5529, 0.3971, 0.3035, 0.6467, 0.4635,
          0.5470, 0.5594, 0.4425, 0.0171, 0.7282, 0.7401, 0.2214, 0.8332],
         [0.5219, 0.1051, 0.9706, 0.2877, 0.1299, 0.0666, 0.4185, 0.7618,
          0.2195, 0.8187, 0.5358, 0.8766, 0.9193, 0.5091, 0.8017, 0.6449],
         [0.3183, 0.9572, 0.0584, 0.9171, 0.8103, 0.9044, 0.7353, 0.4532,
          0.6950, 0.6541, 0.2401, 0.6650, 0.5886, 0.9549, 0.1982, 0.3208],
         [0.8614, 0.3018, 0.3455, 0.6930, 0.4759, 0.6512, 0.5356, 0.0140,
          0.7356, 0.8850, 0.1430

In [20]:
image_tensor.shape

torch.Size([3, 9, 16])

Можем попробовать поменять размер тензора, например, [вытянуть его в вектор](https://pytorch.org/docs/stable/generated/torch.ravel.html):

In [21]:
image_tensor.ravel()

tensor([0.5659, 0.4856, 0.8741, 0.8532, 0.5410, 0.2716, 0.9388, 0.9431, 0.2070,
        0.2638, 0.1503, 0.0352, 0.0994, 0.4392, 0.2082, 0.1029, 0.6235, 0.8818,
        0.1516, 0.7461, 0.6297, 0.5082, 0.6128, 0.6746, 0.5185, 0.2862, 0.4001,
        0.0150, 0.7387, 0.9917, 0.2264, 0.4910, 0.4452, 0.0088, 0.8830, 0.1260,
        0.5734, 0.6298, 0.6813, 0.6440, 0.2537, 0.4155, 0.2459, 0.1554, 0.7389,
        0.4819, 0.9495, 0.7055, 0.5484, 0.0634, 0.5370, 0.5529, 0.3971, 0.3035,
        0.6467, 0.4635, 0.5470, 0.5594, 0.4425, 0.0171, 0.7282, 0.7401, 0.2214,
        0.8332, 0.5219, 0.1051, 0.9706, 0.2877, 0.1299, 0.0666, 0.4185, 0.7618,
        0.2195, 0.8187, 0.5358, 0.8766, 0.9193, 0.5091, 0.8017, 0.6449, 0.3183,
        0.9572, 0.0584, 0.9171, 0.8103, 0.9044, 0.7353, 0.4532, 0.6950, 0.6541,
        0.2401, 0.6650, 0.5886, 0.9549, 0.1982, 0.3208, 0.8614, 0.3018, 0.3455,
        0.6930, 0.4759, 0.6512, 0.5356, 0.0140, 0.7356, 0.8850, 0.1430, 0.6780,
        0.8761, 0.5410, 0.5917, 0.2612, 

In [22]:
image_tensor.ravel().shape

torch.Size([432])

In [23]:
h * w * c

432

Посчитаем количество элементов в тензоре с помощью [специальной функции](https://pytorch.org/docs/stable/generated/torch.numel.html):

In [24]:
image_tensor.numel()

432

In [25]:
h = 2
w = 3
c = 3

shape = (c, h, w)

image_tensor = torch.rand(shape)

image_tensor

tensor([[[0.7421, 0.7784, 0.7046],
         [0.8762, 0.7117, 0.5729]],

        [[0.1995, 0.0234, 0.3698],
         [0.2979, 0.7807, 0.2675]],

        [[0.6964, 0.7178, 0.0089],
         [0.0520, 0.8601, 0.0668]]])

Попробуем поменять размер с помощью функции [reshape](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape):

In [26]:
image_tensor.reshape(c, h * w).shape

torch.Size([3, 6])

Попробуем собрать из нескольких тензоров один большой:

[torch.cat](https://pytorch.org/docs/stable/generated/torch.cat.html#torch.cat)

In [27]:
x = torch.randn(2, 3)

In [28]:
x

tensor([[ 0.8353, -0.9973, -0.5719],
        [-0.4893,  0.4784, -0.8199]])

In [31]:
torch.cat((x, x, x), dim=0).shape

torch.Size([6, 3])

In [32]:
torch.cat((x, x, x), dim=1).shape

torch.Size([2, 9])

In [33]:
x = torch.randn(3, 3)
y = torch.randn(5, 3)
z = torch.randn(1, 3)

for tensor in [x, y, z]:
    print(tensor)

torch.cat((x, y, z), dim=0).shape

tensor([[ 0.1082, -1.0981, -1.1849],
        [-1.3835, -1.5329,  1.2110],
        [-0.5903,  0.7240,  0.2976]])
tensor([[-2.0249,  0.3516, -0.2840],
        [ 0.7285,  1.4730,  0.2796],
        [-0.8175,  1.2816, -0.2864],
        [-1.5737,  1.9519, -0.6376],
        [ 0.8371,  0.2514, -0.9651]])
tensor([[-0.7112,  1.9860,  0.2757]])


torch.Size([9, 3])

In [34]:
x = torch.randn(2, 3)
y = torch.randn(2, 5)
z = torch.randn(2, 1)

for tensor in [x, y, z]:
    print(tensor)

torch.cat((x, y, z), dim=1).shape

tensor([[-0.2393,  1.3657, -0.2002],
        [ 0.7523,  0.7820, -0.1694]])
tensor([[-0.6644,  0.1965, -0.0461,  0.3021,  0.9194],
        [ 1.2949,  0.5571, -0.3281, -1.0994, -0.4786]])
tensor([[-0.0278],
        [ 0.1239]])


torch.Size([2, 9])

Теперь добавим дополнительную ось:

[torch.unsqueeze](https://pytorch.org/docs/stable/generated/torch.unsqueeze.html)

In [35]:
x = torch.rand(2, 3)

print(x)
print()
print(x.unsqueeze(0), x.unsqueeze(0).shape)
print()
print(x.unsqueeze(1), x.unsqueeze(1).shape)
print()
print(x.unsqueeze(2), x.unsqueeze(2).shape)
print()
print(x.unsqueeze(2), x.unsqueeze(-1).shape)

tensor([[0.7009, 0.8385, 0.0081],
        [0.2694, 0.6160, 0.8226]])

tensor([[[0.7009, 0.8385, 0.0081],
         [0.2694, 0.6160, 0.8226]]]) torch.Size([1, 2, 3])

tensor([[[0.7009, 0.8385, 0.0081]],

        [[0.2694, 0.6160, 0.8226]]]) torch.Size([2, 1, 3])

tensor([[[0.7009],
         [0.8385],
         [0.0081]],

        [[0.2694],
         [0.6160],
         [0.8226]]]) torch.Size([2, 3, 1])

tensor([[[0.7009],
         [0.8385],
         [0.0081]],

        [[0.2694],
         [0.6160],
         [0.8226]]]) torch.Size([2, 3, 1])


Уберем лишние оси (где размер единичка):

In [36]:
x = torch.rand(1, 2, 1, 3)

print(x)
print()
print(x.squeeze(), x.squeeze().shape)
print()
print(x.squeeze(0), x.squeeze(0).shape)

tensor([[[[0.5453, 0.5538, 0.6544]],

         [[0.8144, 0.8061, 0.8074]]]])

tensor([[0.5453, 0.5538, 0.6544],
        [0.8144, 0.8061, 0.8074]]) torch.Size([2, 3])

tensor([[[0.5453, 0.5538, 0.6544]],

        [[0.8144, 0.8061, 0.8074]]]) torch.Size([2, 1, 3])


Теперь поговорим про типы данных в тензорах. По умолчанию в тензорах лежат числа в torch.float32 для вещественных и torch.int64 для целочисленных.

In [37]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9])

tensor

tensor([1.5000, 2.2000, 3.7000, 4.9000])

In [38]:
tensor.dtype

torch.float32

In [39]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9], dtype=torch.float16)

tensor

tensor([1.5000, 2.1992, 3.6992, 4.8984], dtype=torch.float16)

In [40]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9], dtype=torch.bfloat16)

tensor

tensor([1.5000, 2.2031, 3.7031, 4.9062], dtype=torch.bfloat16)

In [41]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9], dtype=torch.float64)

tensor

tensor([1.5000, 2.2000, 3.7000, 4.9000], dtype=torch.float64)

In [42]:
tensor = torch.tensor([15, 22, 37, 49])

tensor

tensor([15, 22, 37, 49])

In [43]:
tensor.dtype

torch.int64

In [44]:
tensor = torch.tensor([15, 22, 37, 49], dtype=torch.int32)

tensor

tensor([15, 22, 37, 49], dtype=torch.int32)

In [45]:
tensor = torch.tensor([15, 22, 37, 49], dtype=torch.int16)

tensor

tensor([15, 22, 37, 49], dtype=torch.int16)

Размещение тензора на GPU:

In [46]:
!nvidia-smi

Tue Oct 21 11:03:44 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [47]:
print(torch.cuda.is_available())
print(torch.cuda.get_device_name())

True
Tesla T4


In [ ]:
!nvidia-smi

Fri Oct 11 12:12:57 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [48]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

print(device)

cuda:0


In [49]:
tensor = torch.tensor([15, 22, 37, 49], device=device)

tensor

tensor([15, 22, 37, 49], device='cuda:0')

In [50]:
tensor = torch.tensor([15, 22, 37, 49])

print(tensor)

tensor = tensor.to(device)

tensor

tensor([15, 22, 37, 49])


tensor([15, 22, 37, 49], device='cuda:0')

In [51]:
tensor.to(torch.int32)

tensor([15, 22, 37, 49], device='cuda:0', dtype=torch.int32)

In [52]:
tensor = tensor.cpu()

tensor

tensor([15, 22, 37, 49])

In [53]:
tensor.cuda()

tensor([15, 22, 37, 49], device='cuda:0')

In [54]:
tensor.device

device(type='cpu')

In [55]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

a + b

tensor([[0.9085, 0.9078, 1.4289],
        [1.2063, 1.5381, 0.9822]])

In [56]:
a = a.to(device)

a + b

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [57]:
b = b.to(device)

a + b

tensor([[0.9085, 0.9078, 1.4289],
        [1.2063, 1.5381, 0.9822]], device='cuda:0')

### Операции с тензорами

Большая часть операций с тензорами хорошо описана в их [документации](https://pytorch.org/docs/stable/torch.html), разберем основные:

In [58]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

a, b

(tensor([[0.4702, 0.9727, 0.1850],
         [0.1265, 0.7198, 0.5724]]),
 tensor([[0.4522, 0.5965, 0.9128],
         [0.0782, 0.1048, 0.1003]]))

In [59]:
# поэлементные

print(a + b)

print()

print(torch.add(a, b))

print()

print(a.add(b))

tensor([[0.9224, 1.5692, 1.0978],
        [0.2047, 0.8246, 0.6727]])

tensor([[0.9224, 1.5692, 1.0978],
        [0.2047, 0.8246, 0.6727]])

tensor([[0.9224, 1.5692, 1.0978],
        [0.2047, 0.8246, 0.6727]])


In [60]:
print(a - b)

print()

print(torch.sub(a, b))

print()

print(a.sub(b))

tensor([[ 0.0180,  0.3762, -0.7278],
        [ 0.0482,  0.6150,  0.4720]])

tensor([[ 0.0180,  0.3762, -0.7278],
        [ 0.0482,  0.6150,  0.4720]])

tensor([[ 0.0180,  0.3762, -0.7278],
        [ 0.0482,  0.6150,  0.4720]])


In [61]:
print(a * b)

print()

print(torch.mul(a, b))

print()

print(a.mul(b))

tensor([[0.2126, 0.5802, 0.1689],
        [0.0099, 0.0754, 0.0574]])

tensor([[0.2126, 0.5802, 0.1689],
        [0.0099, 0.0754, 0.0574]])

tensor([[0.2126, 0.5802, 0.1689],
        [0.0099, 0.0754, 0.0574]])


In [62]:
print(a / b)

print()

print(torch.div(a, b))

print()

print(a.div(b))

tensor([[1.0397, 1.6306, 0.2027],
        [1.6162, 6.8682, 5.7055]])

tensor([[1.0397, 1.6306, 0.2027],
        [1.6162, 6.8682, 5.7055]])

tensor([[1.0397, 1.6306, 0.2027],
        [1.6162, 6.8682, 5.7055]])


In [63]:
a = torch.rand(2, 3)
b = torch.rand(3, 4)
c = torch.rand(5, 5)

a, b, c

(tensor([[0.7593, 0.9876, 0.8865],
         [0.7988, 0.5943, 0.5754]]),
 tensor([[0.3486, 0.8552, 0.8280, 0.3778],
         [0.4579, 0.6674, 0.6430, 0.7305],
         [0.5700, 0.6341, 0.4491, 0.7445]]),
 tensor([[0.0021, 0.2340, 0.5900, 0.1635, 0.0419],
         [0.1692, 0.6658, 0.5231, 0.5163, 0.2044],
         [0.0453, 0.1343, 0.4762, 0.0810, 0.2671],
         [0.2200, 0.6649, 0.1687, 0.3251, 0.0616],
         [0.0217, 0.5090, 0.4744, 0.7829, 0.4927]]))

In [64]:
# матричные операции

print(a @ b, (a @ b).shape)

print()

print(torch.matmul(a, b), torch.matmul(a, b).shape)

print()

print(c.trace())

print()

print(c.exp())

tensor([[1.2222, 1.8705, 1.6618, 1.6682],
        [0.8786, 1.4446, 1.3020, 1.1643]]) torch.Size([2, 4])

tensor([[1.2222, 1.8705, 1.6618, 1.6682],
        [0.8786, 1.4446, 1.3020, 1.1643]]) torch.Size([2, 4])

tensor(1.9619)

tensor([[1.0021, 1.2637, 1.8040, 1.1776, 1.0428],
        [1.1844, 1.9461, 1.6872, 1.6758, 1.2268],
        [1.0463, 1.1438, 1.6099, 1.0844, 1.3062],
        [1.2461, 1.9444, 1.1837, 1.3842, 1.0636],
        [1.0219, 1.6635, 1.6071, 2.1878, 1.6367]])


### [Автоматическое дифференцирование](https://pytorch.org/docs/stable/notes/autograd.html)

In [65]:
x = torch.rand(5)

x

tensor([0.5705, 0.5962, 0.6205, 0.0895, 0.9650])

In [66]:
w = torch.rand(3, 5, requires_grad=True)

w

tensor([[0.7582, 0.3935, 0.5391, 0.6990, 0.6785],
        [0.5844, 0.7947, 0.5260, 0.6221, 0.3664],
        [0.7281, 0.2928, 0.8177, 0.9539, 0.0357]], requires_grad=True)

In [67]:
print(w.grad)

None


In [68]:
first_z = torch.empty(3)

first_z

tensor([0.2214, 0.0000, 0.2221])

In [69]:
for i in range(3):
    first_z[i] = torch.sum(w[i] * x)

first_z

tensor([1.7190, 1.5429, 1.2171], grad_fn=<CopySlices>)

In [70]:
z = torch.matmul(x, w.t())

z

tensor([1.7190, 1.5429, 1.2171], grad_fn=<SqueezeBackward4>)

In [71]:
v = torch.rand(3, requires_grad=True)

v

tensor([0.6429, 0.4176, 0.9466], requires_grad=True)

In [72]:
print(v.grad)

None


In [73]:
y = torch.sum(z * v)

y

tensor(2.9018, grad_fn=<SumBackward0>)

In [74]:
y.item()

2.9017515182495117

In [75]:
loss = torch.mean((y - 2) ** 2)

In [76]:
loss

tensor(0.8132, grad_fn=<MeanBackward0>)

In [77]:
print(f'{x.grad=}\n')
print(f'{w.grad=}\n')
print(f'{z=}\n')
print(f'{v.grad=}\n')

x.grad=None

w.grad=None

z=tensor([1.7190, 1.5429, 1.2171], grad_fn=<SqueezeBackward4>)

v.grad=None



In [78]:
loss.backward()

In [79]:
print(f'{x.grad=}\n')
print(f'{w.grad=}\n')
print(f'{z.grad=}\n')
print(f'{v.grad=}\n')

x.grad=None

w.grad=tensor([[0.6616, 0.6913, 0.7195, 0.1037, 1.1190],
        [0.4297, 0.4491, 0.4674, 0.0674, 0.7269],
        [0.9740, 1.0179, 1.0594, 0.1527, 1.6476]])

z.grad=None

v.grad=tensor([3.1002, 2.7826, 2.1951])



/tmp/ipython-input-162867685.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  print(f'{z.grad=}\n')


In [80]:
a = torch.rand(1, requires_grad=True)
b = torch.rand(1, requires_grad=True)

a, b

(tensor([0.4290], requires_grad=True), tensor([0.0235], requires_grad=True))

In [81]:
loss = (a - b)

loss

tensor([0.4055], grad_fn=<SubBackward0>)

In [82]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [83]:
loss.backward()

In [84]:
print(f'{a.grad=}\n')  # 1
print(f'{b.grad=}\n')  # -1

a.grad=tensor([1.])

b.grad=tensor([-1.])



In [85]:
a.grad.zero_()
b.grad.zero_()

tensor([0.])

In [86]:
loss = (a - b) ** 2

loss

tensor([0.1644], grad_fn=<PowBackward0>)

In [87]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=tensor([0.])

b.grad=tensor([0.])



In [88]:
loss.backward()

In [89]:
print(f'{a.grad=}\n')  # 2 * (a - b)
print(f'{b.grad=}\n')  # -2 * (a - b)

a.grad=tensor([0.8109])

b.grad=tensor([-0.8109])



In [90]:
2 * (a - b)

tensor([0.8109], grad_fn=<MulBackward0>)

In [91]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=True)

a, b

(tensor([[0.5573, 0.6276, 0.7296, 0.9110, 0.9180],
         [0.1603, 0.6766, 0.8380, 0.7338, 0.5713],
         [0.6956, 0.9155, 0.9926, 0.0371, 0.7031]], requires_grad=True),
 tensor([[0.3035, 0.9763, 0.5774, 0.3633, 0.1770],
         [0.4977, 0.1234, 0.9490, 0.7939, 0.7114],
         [0.9317, 0.2954, 0.3516, 0.3140, 0.4911]], requires_grad=True))

In [92]:
loss = torch.mean(a * b)

loss

tensor(0.3512, grad_fn=<MeanBackward0>)

In [93]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [94]:
loss.backward()

In [95]:
print(f'{a.grad=}\n')  # b / (3 * 5)
print(f'{b.grad=}\n')  # a / (3 * 5)

a.grad=tensor([[0.0202, 0.0651, 0.0385, 0.0242, 0.0118],
        [0.0332, 0.0082, 0.0633, 0.0529, 0.0474],
        [0.0621, 0.0197, 0.0234, 0.0209, 0.0327]])

b.grad=tensor([[0.0372, 0.0418, 0.0486, 0.0607, 0.0612],
        [0.0107, 0.0451, 0.0559, 0.0489, 0.0381],
        [0.0464, 0.0610, 0.0662, 0.0025, 0.0469]])



In [96]:
a / 15

tensor([[0.0372, 0.0418, 0.0486, 0.0607, 0.0612],
        [0.0107, 0.0451, 0.0559, 0.0489, 0.0381],
        [0.0464, 0.0610, 0.0662, 0.0025, 0.0469]], grad_fn=<DivBackward0>)

In [97]:
b / 15

tensor([[0.0202, 0.0651, 0.0385, 0.0242, 0.0118],
        [0.0332, 0.0082, 0.0633, 0.0529, 0.0474],
        [0.0621, 0.0197, 0.0234, 0.0209, 0.0327]], grad_fn=<DivBackward0>)

In [98]:
a = torch.rand(3, 5, requires_grad=True)

print(f'{a=}\n')

loss1 = torch.sum(a ** 2) # 2a
loss2 = torch.sum(a) # 1

print(f'{a.grad=}\n')

loss1.backward()

print(f'{a.grad=}\n')

loss2.backward()

print(f'{a.grad=}\n')

a=tensor([[0.5586, 0.6786, 0.3314, 0.8877, 0.1858],
        [0.5323, 0.6959, 0.2882, 0.9602, 0.2547],
        [0.6039, 0.2470, 0.0069, 0.9868, 0.2323]], requires_grad=True)

a.grad=None

a.grad=tensor([[1.1173, 1.3571, 0.6627, 1.7753, 0.3715],
        [1.0646, 1.3919, 0.5763, 1.9203, 0.5093],
        [1.2078, 0.4940, 0.0137, 1.9736, 0.4646]])

a.grad=tensor([[2.1173, 2.3571, 1.6627, 2.7753, 1.3715],
        [2.0646, 2.3919, 1.5763, 2.9203, 1.5093],
        [2.2078, 1.4940, 1.0137, 2.9736, 1.4646]])



In [99]:
print(f'{2*a=}\n')
print(f'{2*a+1=}')

2*a=tensor([[1.1173, 1.3571, 0.6627, 1.7753, 0.3715],
        [1.0646, 1.3919, 0.5763, 1.9203, 0.5093],
        [1.2078, 0.4940, 0.0137, 1.9736, 0.4646]], grad_fn=<MulBackward0>)

2*a+1=tensor([[2.1173, 2.3571, 1.6627, 2.7753, 1.3715],
        [2.0646, 2.3919, 1.5763, 2.9203, 1.5093],
        [2.2078, 1.4940, 1.0137, 2.9736, 1.4646]], grad_fn=<AddBackward0>)


In [100]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=False)

a, b

(tensor([[0.0201, 0.4882, 0.7795, 0.8308, 0.9343],
         [0.5185, 0.2816, 0.3613, 0.8153, 0.9036],
         [0.2181, 0.8752, 0.2111, 0.1753, 0.0288]], requires_grad=True),
 tensor([[0.3798, 0.8647, 0.1696, 0.0439, 0.5862],
         [0.6562, 0.8805, 0.2868, 0.0200, 0.8501],
         [0.2325, 0.3876, 0.3131, 0.6951, 0.6742]]))

In [101]:
loss = torch.sum(a - b)

loss

tensor(0.4014, grad_fn=<SumBackward0>)

In [102]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [103]:
loss.backward()

In [104]:
print(f'{a.grad=}\n')  # all ones
print(f'{b.grad=}\n')  # None

a.grad=tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

b.grad=None



In [105]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=True)

a, b

(tensor([[0.7667, 0.5396, 0.7807, 0.7693, 0.8400],
         [0.3467, 0.2536, 0.4766, 0.4898, 0.7731],
         [0.1961, 0.7171, 0.1603, 0.0817, 0.2429]], requires_grad=True),
 tensor([[0.6920, 0.4796, 0.9611, 0.1414, 0.0161],
         [0.1214, 0.3315, 0.7545, 0.8874, 0.7157],
         [0.5509, 0.7974, 0.7169, 0.7909, 0.6629]], requires_grad=True))

In [106]:
with torch.no_grad():
    loss = torch.sum(a - b)

loss

tensor(-1.1856)

In [107]:
loss = torch.sum(a - b)
loss

tensor(-1.1856, grad_fn=<SumBackward0>)

In [108]:
loss

tensor(-1.1856, grad_fn=<SumBackward0>)

In [109]:
loss.backward()

In [110]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=True)

a, b

(tensor([[0.1280, 0.7201, 0.6155, 0.5145, 0.0703],
         [0.6379, 0.6930, 0.2323, 0.9205, 0.2729],
         [0.7576, 0.6330, 0.9570, 0.7958, 0.9663]], requires_grad=True),
 tensor([[0.2217, 0.8707, 0.2356, 0.1273, 0.5644],
         [0.9958, 0.9201, 0.7527, 0.4298, 0.3294],
         [0.7500, 0.6554, 0.7436, 0.8508, 0.8118]], requires_grad=True))

In [111]:
with torch.inference_mode():
    loss = torch.sum(a - b)

loss

tensor(-0.3442)

In [112]:
loss.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [113]:
with torch.no_grad():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)

    loss = torch.sum(a + b)

    print(f'{loss=}')

    loss.backward()

loss=tensor(15.3643)


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [114]:
a

tensor([[0.4031, 0.2878, 0.2806, 0.1452, 0.2215],
        [0.0947, 0.8064, 0.6906, 0.8456, 0.8647],
        [0.4381, 0.8831, 0.2962, 0.6599, 0.6155]], requires_grad=True)

In [115]:
loss2 = torch.sum(a + b)

loss2

tensor(15.3643, grad_fn=<SumBackward0>)

In [116]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [117]:
loss2.backward()

In [118]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

b.grad=tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])



In [119]:
with torch.inference_mode():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)

    loss = torch.sum(a + b)

    print(f'{loss=}')

    loss.backward()

loss=tensor(12.8953)


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [120]:
loss2 = torch.sum(a + b)

loss2

tensor(12.8953)

In [121]:
@torch.no_grad()
def foo():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)

    loss = torch.mean(a + b)

    print(f'{loss=}')

    return a, b

In [122]:
a, b = foo()

loss=tensor(1.0089)


In [123]:
torch.mean(a - b)

tensor(-0.0810, grad_fn=<MeanBackward0>)

In [124]:
@torch.inference_mode()
def foo():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)

    loss = torch.mean(a + b)

    print(f'{loss=}')

    return a, b

In [125]:
a, b = foo()

loss=tensor(1.0254)


In [126]:
torch.mean(a - b)

tensor(-0.0123)

In [127]:
a.requires_grad = False

## Полносвязные слои и функции активации в `PyTorch`

In [128]:
from torch import nn

In [129]:
import torch.nn as nn

### Полносвязный слой

>$y_j = \sum\limits_{i=1}^{n}x_iw_{ji} + b_j$


In [130]:
layer = nn.Linear(in_features=5, out_features=3)

In [131]:
layer

Linear(in_features=5, out_features=3, bias=True)

In [132]:
layer.weight

Parameter containing:
tensor([[-0.2062, -0.4079, -0.3855, -0.0672, -0.3426],
        [ 0.3755,  0.1416, -0.4060,  0.1774,  0.3517],
        [-0.2534, -0.0284, -0.2414,  0.1724, -0.0363]], requires_grad=True)

In [133]:
layer.weight.shape

torch.Size([3, 5])

In [134]:
layer.bias

Parameter containing:
tensor([ 0.1610, -0.0944, -0.0180], requires_grad=True)

In [135]:
layer.bias.shape

torch.Size([3])

In [136]:
layer = nn.Linear(in_features=5, out_features=3, bias=False)

In [137]:
layer.bias is None

True

In [ ]:
# layer.__call__

In [138]:
x = torch.randn(5)

print(layer(x))

tensor([ 0.0326,  1.7749, -0.6895], grad_fn=<SqueezeBackward4>)


In [139]:
layer1 = nn.Linear(in_features=5, out_features=3)
layer2 = nn.Linear(in_features=3, out_features=1)

layer2(layer1(x))

tensor([-0.2491], grad_fn=<ViewBackward0>)

### Функции активации

> Сигмоида $f(x) = \dfrac{1}{1 + e^{-x}}$

In [140]:
activation = nn.Sigmoid()

In [141]:
x = torch.randn(5)

print(x)

print(activation(x))

tensor([-0.4460,  2.2858,  0.2467,  0.2214, -0.4973])
tensor([0.3903, 0.9077, 0.5614, 0.5551, 0.3782])


> ReLU $f(x) = \max(0, x)$

In [142]:
activation = nn.ReLU()

In [143]:
x = torch.randn(5)

print(x)

print(activation(x))

tensor([ 0.1011,  1.4305, -0.6399,  0.2537,  1.9115])
tensor([0.1011, 1.4305, 0.0000, 0.2537, 1.9115])


> Leaky ReLU $f(x) = \max(0, x) + \alpha \min(0, x)$

In [144]:
activation = nn.LeakyReLU(negative_slope=0.001)

In [145]:
x = torch.randn(5)

print(x)

print(activation(x))

tensor([ 0.3737, -1.3471,  1.9151,  1.1647, -0.4972])
tensor([ 3.7372e-01, -1.3471e-03,  1.9151e+00,  1.1647e+00, -4.9721e-04])


In [146]:
layer1 = nn.Linear(in_features=5, out_features=3)
activation = nn.LeakyReLU(negative_slope=0.001)
layer2 = nn.Linear(in_features=3, out_features=1)

layer2(activation(layer1(x)))

tensor([-0.0091], grad_fn=<ViewBackward0>)

## Градиентный спуск своими руками

In [147]:
n_features = 2
n_objects = 300

torch.manual_seed(0)

w_true = torch.randn(n_features)
b_true = torch.randn(1)

x = (torch.rand(n_objects, n_features) - 0.5) * 10 * (torch.arange(n_features) * 2 + 1)
y = torch.matmul(x, w_true) + torch.randn(n_objects) + b_true

In [148]:
x.shape

torch.Size([300, 2])

In [149]:
y.shape

torch.Size([300])

In [150]:
n_steps = 200
step_size = 1e-2

In [151]:
w = torch.rand(n_features, requires_grad=True)
b = torch.rand(1, requires_grad=True)

for i in range(n_steps):
    y_pred = torch.matmul(x, w) + b

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 10 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

#     print(f'{w.grad=}\n')
#     print(f'{b.grad=}\n')

    with torch.no_grad():
        w -= w.grad * step_size
        b -= b.grad * step_size

    w.grad.zero_()
    b.grad.zero_()

MSE на шаге 1 23.65750
MSE на шаге 2 15.53605
MSE на шаге 3 12.11575
MSE на шаге 4 10.36995
MSE на шаге 5 9.30175
MSE на шаге 6 8.55659
MSE на шаге 7 7.99169
MSE на шаге 8 7.53972
MSE на шаге 9 7.16377
MSE на шаге 10 6.84131
MSE на шаге 11 6.55765
MSE на шаге 12 6.30292
MSE на шаге 13 6.07033
MSE на шаге 14 5.85515
MSE на шаге 15 5.65409
MSE на шаге 16 5.46478
MSE на шаге 17 5.28555
MSE на шаге 18 5.11514
MSE на шаге 19 4.95265
MSE на шаге 20 4.79736
MSE на шаге 21 4.64871
MSE на шаге 31 3.45555
MSE на шаге 41 2.65631
MSE на шаге 51 2.11964
MSE на шаге 61 1.75925
MSE на шаге 71 1.51724
MSE на шаге 81 1.35471
MSE на шаге 91 1.24558
MSE на шаге 101 1.17229
MSE на шаге 111 1.12307
MSE на шаге 121 1.09002
MSE на шаге 131 1.06782
MSE на шаге 141 1.05292
MSE на шаге 151 1.04291
MSE на шаге 161 1.03619
MSE на шаге 171 1.03168
MSE на шаге 181 1.02864
MSE на шаге 191 1.02661


In [152]:
x.shape

torch.Size([300, 2])

In [153]:
layer = nn.Linear(in_features=n_features, out_features=1)


for i in range(n_steps):
    y_pred = layer(x)

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 10 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer.weight -= layer.weight.grad * step_size
        layer.bias -= layer.bias.grad * step_size

#     layer.weight.grad.zero_()
#     layer.bias.grad.zero_()

    layer.zero_grad()

MSE на шаге 1 61.04561
MSE на шаге 2 43.79891
MSE на шаге 3 37.83810
MSE на шаге 4 35.47980
MSE на шаге 5 34.33194
MSE на шаге 6 33.63191
MSE на шаге 7 33.12450
MSE на шаге 8 32.71631
MSE на шаге 9 32.36813
MSE на шаге 10 32.06060
MSE на шаге 11 31.78264
MSE на шаге 12 31.52728
MSE на шаге 13 31.28983
MSE на шаге 14 31.06706
MSE на шаге 15 30.85670
MSE на шаге 16 30.65709
MSE на шаге 17 30.46700
MSE на шаге 18 30.28552
MSE на шаге 19 30.11194
MSE на шаге 20 29.94569
MSE на шаге 21 29.78632
MSE на шаге 31 28.50329
MSE на шаге 41 27.64299
MSE на шаге 51 27.06530
MSE на шаге 61 26.67736
MSE на шаге 71 26.41685
MSE на шаге 81 26.24191
MSE на шаге 91 26.12442
MSE на шаге 101 26.04553
MSE на шаге 111 25.99255
MSE на шаге 121 25.95697
MSE на шаге 131 25.93308
MSE на шаге 141 25.91704
MSE на шаге 151 25.90627
MSE на шаге 161 25.89903
MSE на шаге 171 25.89417
MSE на шаге 181 25.89091
MSE на шаге 191 25.88872


In [154]:
layer(x)

tensor([[-2.7148],
        [-2.7140],
        [-2.7176],
        [-2.7166],
        [-2.7120],
        [-2.7163],
        [-2.7139],
        [-2.7192],
        [-2.7145],
        [-2.6967],
        [-2.7170],
        [-2.7219],
        [-2.7158],
        [-2.7131],
        [-2.7239],
        [-2.7108],
        [-2.7082],
        [-2.7042],
        [-2.7162],
        [-2.7095],
        [-2.7165],
        [-2.7121],
        [-2.7090],
        [-2.7013],
        [-2.7051],
        [-2.7159],
        [-2.7101],
        [-2.7203],
        [-2.7056],
        [-2.7133],
        [-2.7121],
        [-2.7177],
        [-2.7136],
        [-2.7090],
        [-2.7043],
        [-2.7071],
        [-2.7277],
        [-2.6977],
        [-2.7091],
        [-2.7108],
        [-2.7043],
        [-2.7117],
        [-2.7072],
        [-2.7181],
        [-2.7084],
        [-2.7164],
        [-2.7069],
        [-2.7150],
        [-2.7219],
        [-2.7148],
        [-2.7137],
        [-2.7203],
        [-2.

In [155]:
layer(x).shape

torch.Size([300, 1])

In [156]:
y.shape

torch.Size([300])

In [157]:
(layer(x) - y).shape

torch.Size([300, 300])

In [158]:
layer(x).ravel().shape

torch.Size([300])

In [159]:
(layer(x).ravel() - y).shape

torch.Size([300])

In [160]:
layer = nn.Linear(in_features=n_features, out_features=1)

for i in range(n_steps):
    y_pred = layer(x).ravel()

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 10 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer.weight -= layer.weight.grad * step_size
        layer.bias -= layer.bias.grad * step_size

    layer.zero_grad()

MSE на шаге 1 24.25042
MSE на шаге 2 12.14032
MSE на шаге 3 7.56999
MSE на шаге 4 5.56054
MSE на шаге 5 4.51142
MSE на шаге 6 3.87844
MSE на шаге 7 3.45734
MSE на шаге 8 3.15958
MSE на шаге 9 2.94016
MSE на шаге 10 2.77302
MSE на шаге 11 2.64175
MSE на шаге 12 2.53550
MSE на шаге 13 2.44699
MSE на шаге 14 2.37122
MSE на шаге 15 2.30476
MSE на шаге 16 2.24524
MSE на шаге 17 2.19103
MSE на шаге 18 2.14098
MSE на шаге 19 2.09427
MSE на шаге 20 2.05035
MSE на шаге 21 2.00880
MSE на шаге 31 1.68252
MSE на шаге 41 1.46566
MSE на шаге 51 1.32008
MSE на шаге 61 1.22232
MSE на шаге 71 1.15667
MSE на шаге 81 1.11258
MSE на шаге 91 1.08297
MSE на шаге 101 1.06309
MSE на шаге 111 1.04974
MSE на шаге 121 1.04078
MSE на шаге 131 1.03476
MSE на шаге 141 1.03071
MSE на шаге 151 1.02800
MSE на шаге 161 1.02617
MSE на шаге 171 1.02495
MSE на шаге 181 1.02413
MSE на шаге 191 1.02358


In [161]:
n_features = 5
n_objects = 300

torch.manual_seed(0)

w_true = torch.randn(n_features)

x = (torch.rand(n_objects, n_features) - 0.5) * 10 * (torch.arange(n_features) * 2 + 1)
y = torch.matmul(x, w_true) + torch.randn(n_objects)

In [162]:
x.shape, y.shape

(torch.Size([300, 5]), torch.Size([300]))

In [163]:
n_steps = 500
step_size = 1e-3

In [164]:
layer = nn.Linear(in_features=n_features, out_features=1)

for i in range(n_steps):
    y_pred = layer(x).ravel()

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 50 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer.weight -= layer.weight.grad * step_size
        layer.bias -= layer.bias.grad * step_size

    layer.zero_grad()

MSE на шаге 1 1522.64282
MSE на шаге 2 345.22867
MSE на шаге 3 134.71323
MSE на шаге 4 69.14162
MSE на шаге 5 45.61798
MSE на шаге 6 36.15922
MSE на шаге 7 31.74179
MSE на шаге 8 29.24493
MSE на шаге 9 27.53952
MSE на шаге 10 26.19924
MSE на шаге 11 25.05364
MSE на шаге 12 24.02866
MSE на шаге 13 23.08827
MSE на шаге 14 22.21260
MSE на шаге 15 21.38941
MSE на шаге 16 20.61047
MSE на шаге 17 19.86992
MSE на шаге 18 19.16343
MSE на шаге 19 18.48770
MSE на шаге 20 17.84015
MSE на шаге 51 6.27401
MSE на шаге 101 1.74083
MSE на шаге 151 1.02593
MSE на шаге 201 0.91269
MSE на шаге 251 0.89435
MSE на шаге 301 0.89104
MSE на шаге 351 0.89019
MSE на шаге 401 0.88977
MSE на шаге 451 0.88948


In [165]:
n_steps = 1000
step_size = 3e-4

In [166]:
layer1 = nn.Linear(in_features=n_features, out_features=3)
layer2 = nn.Linear(in_features=3, out_features=1)
activation = nn.ReLU()


for i in range(n_steps):
    y_pred = layer2(activation(layer1(x))).ravel()

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 50 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer1.weight -= layer1.weight.grad * step_size
        layer1.bias -= layer1.bias.grad * step_size
        layer2.weight -= layer2.weight.grad * step_size
        layer2.bias -= layer2.bias.grad * step_size

    layer1.zero_grad()
    layer2.zero_grad()

MSE на шаге 1 2065.53369
MSE на шаге 2 1941.40063
MSE на шаге 3 1890.73816
MSE на шаге 4 1863.17334
MSE на шаге 5 1843.74536
MSE на шаге 6 1825.21838
MSE на шаге 7 1803.15234
MSE на шаге 8 1775.96985
MSE на шаге 9 1741.44421
MSE на шаге 10 1696.50024
MSE на шаге 11 1638.66467
MSE на шаге 12 1570.60828
MSE на шаге 13 1498.17651
MSE на шаге 14 1426.69543
MSE на шаге 15 1361.06189
MSE на шаге 16 1304.04333
MSE на шаге 17 1252.44177
MSE на шаге 18 1201.12512
MSE на шаге 19 1142.44922
MSE на шаге 20 1069.69434
MSE на шаге 51 10.77816
MSE на шаге 101 5.31390
MSE на шаге 151 3.22006
MSE на шаге 201 2.08225
MSE на шаге 251 1.45981
MSE на шаге 301 1.16964
MSE на шаге 351 1.03444
MSE на шаге 401 0.97123
MSE на шаге 451 0.94166
MSE на шаге 501 0.92668
MSE на шаге 551 0.91742
MSE на шаге 601 0.91137
MSE на шаге 651 0.90724
MSE на шаге 701 0.90359
MSE на шаге 751 0.90093
MSE на шаге 801 0.89880
MSE на шаге 851 0.89742
MSE на шаге 901 0.89643
MSE на шаге 951 0.89556


## Подробнее о view, reshape, contiguous и устройстве тензоров

In [201]:
x = torch.arange(2 * 3).reshape(2, 3)
x

tensor([[0, 1, 2],
        [3, 4, 5]])

Грубо говоря, внутри тензор устроен следующим образом. Сырые данные хранятся в одномерном массиве размера количества элементов в тензоре. Также необходимо хранить размер (shape), в данном случае (2, 3), и страйды (stride). Страйды это массив длины размерности тензора, где на i-ой позиции стоит величина, которую надо прибавить к индексу в одномерном массиве, чтобы увеличить индекс в многомерном массиве на 1.

Для матрицы (2,3) страйды будут выглядеть как (3,1). Чтобы перейти на следующую строку нам нужно прибавить 3 к индексу в массиве, чтобы перейти к следующему столбцу добавляем 1 к индексу.

То есть если у нас есть матрица $x[i,j]$ и сырые данные хранятся в массиве $\text{data}$, то
$$
\text{data}_{k} = x[i,j]
$$
$$
k = i * \text{stride}[0] + j * \text{stride}[1]
$$

Это все обобщается на многомерный случай аналогично.

In [203]:
x.storage()

 0
 1
 2
 3
 4
 5
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]

In [204]:
x.stride()

(3, 1)

В данном случае данные лежат "непрерывно" в одномерном массиве. В терминах страйдов это значит, что

$$
stride[-1] = 1
$$
$$
stride[i] = stride[i+1] * dim[i+1]
$$

In [205]:
x.is_contiguous()

True

Зачем все-таки нужны страйды? Чтобы забесплатно производить решейпинг тензора, транспонирование и тд, меняя только этот массив strides, но не копируя сами сырые данные.

Чтобы транспонировать матрицу, достаточно поменять местами страйды у строк и столбцов.

In [206]:
y = x.permute(1, 0)
y

tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [207]:
y.is_contiguous()

False

Данные не изменились.

In [208]:
y.storage()

 0
 1
 2
 3
 4
 5
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]

In [209]:
y.stride()

(1, 3)

Делать view можно только на непрерывный тензор. Решейп в свою очередь "онепрерывит" тензор, скопирует сырые данные и упакует их правильным образом (.contiguous()), а потом уже поменяет шейпы.

In [210]:
y.view(2, 3)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [220]:
y.reshape(2, 3)

tensor([[0, 3, 1],
        [4, 2, 5]])

In [217]:
y.contiguous().view(2, 3)

tensor([[0, 3, 1],
        [4, 2, 5]])

In [218]:
y.contiguous().stride()

(2, 1)

Данные скопирировались после .contiguous()

In [219]:
y.contiguous().storage()

 0
 3
 1
 4
 2
 5
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]

Работа с непрерывными тензорами быстрее, так как необязательно постоянно сопоставлять мульти-индекс тензора с индексом в одномерном массиве. Если операции поэлементные, то можно просто работать с исходным массивом сырых данных.

Однако, надо иметь в виду, что .contiguous() копирует данные, что может быть ботлнеком в некоторых сценариях.