# Введение. Полносвязные слои. Функции активации (ноутбук)

> Начнем осваивать библиотеку `PyTorch`.

## План ноутбука

1. Установка `PyTorch`
1. Введение в `PyTorch`
1. Полносвязные слои и функции активации в `PyTorch`
1. Градиентный спуск своими руками

## Установка `PyTorch`

Мы будем использовать библиотеку для глубинного обучения `PyTorch`, ее можно не устанавливать, можно пользоваться сайтами [Kaggle](kaggle.com) и [Google Colab](colab.research.google.com/) для обучения в облаке (или с учителем?).

Чтобы установить `PyTorch` локально себе на компьютер нужно ответить на два вопроса - какая у вас операционная система и есть ли у вас дискретная видеокарта (GPU) и если есть, то какого производителя. В зависимости от ваших ответов мы получаем три варианта по операционной системе - Linux, Mac и Windows; три варианта по дискретной видеокарте - нет видеокарты (доступен только центральный процессор CPU), есть видеокарта от Nvidia или есть видеокарта от AMD (это производитель именно чипа, конечный вендор может быть другой, например, ASUS, MSI, Palit). Работа с PyTorch с видеокартой от AMD это экзотика, которая выходит за рамки нашего курса, поэтому рассмотрим только варианты *нет видеокарты*/*есть видеокарта от Nvidia*.


Выберите на [сайте](https://pytorch.org/get-started/locally/) подходящие вам варианты операционной системы/видеокарты и скопируйте команду для установки. Разберем подробно самые популярные варианты установки:

### Установка в Linux ([поддерживаемые дистрибутивы](https://pytorch.org/get-started/locally/#supported-linux-distributions))

На линуксе будет работать поддержка `PyTorch` в любой конфигурации, что у вас нет видеокарты, что есть от Nvidia, что от AMD.

Пререквизит для работы с видеокартой от Nvidia - нужно поставить CUDA, это инструмент от компании Nvidia, который позволяет ускорять вычисления на их же ГПУ. Чтобы поставить себе на машину все правильно воспользуйтесь этим [гайдом](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html) от Nvidia.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu` для тех, у кого нет видеокарты.

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116` для тех, у кого есть видеокарта (либо другой `--extra-index-url`, смотрите на сайте PyTorch, в зависимости от версии CUDA).

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch` для тех, у кого нет видеокарты.

`conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge` для тех, у кого есть видеокарта (либо немного другая команда, в зависимости от версии CUDA).

### Установка в Windows

На винде будет работать поддержка `PyTorch` только для видеокарт от Nvidia и без видеокарт вообще.

Пререквизит для работы с видеокартой от Nvidia - нужно поставить CUDA, это инструмент от компании Nvidia, который позволяет ускорять вычисления на их же ГПУ. Чтобы поставить себе на машину все правильно воспользуйтесь этим [гайдом](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html) от Nvidia.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu` для тех, у кого нет видеокарты.

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116` для тех, у кого есть видеокарта (либо другой `--extra-index-url`, смотрите на сайте PyTorch, в зависимости от версии CUDA).

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch` для тех, у кого нет видеокарты.

`conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge` для тех, у кого есть видеокарта (либо немного другая команда, в зависимости от версии CUDA).



### Установка на Mac

На маках есть пока что поддержка `PyTorch` только центрального процессора, чуть позже появится поддержка ускорения на чипах M1, M2, M1 Pro и так далее.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu`

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch`

In [1]:
!nvidia-smi

Fri Oct 17 18:21:40 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.163.01             Driver Version: 550.163.01     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-80GB          Off |   00000000:82:00.0 Off |                    0 |
| N/A   80C    P0            479W /  500W |   65397MiB /  81920MiB |     99%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+-----

## Введение в `PyTorch`

### Тензоры

Тензоры — это специализированная структура данных, по сути это массивы и матрицы. Тензоры очень похожи на массивы в numpy, так что, если у вас хорошо с numpy, то разобраться в PyTorch тензорах будет очень просто. В PyTorch мы используем тензоры для кодирования входных и выходных данных модели, а также параметров модели.

In [2]:
import torch
import numpy as np

### Создание тензоров

Тензор можно создать напрямую из каких-то данных - нам подходят все списки с числами:

In [3]:
some_data = [1, 2, 3, 4]
some_tensor = torch.tensor(some_data)

some_tensor

tensor([1, 2, 3, 4])

In [4]:
some_data = [[1, 2], [3, 4], [5, 6]]
some_tensor = torch.tensor(some_data)

some_tensor

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [5]:
some_data = [[[1], [2]], [[3], [4]], [[5], [6]]]
some_tensor = torch.tensor(some_data)

some_tensor

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

На самом деле про "все" списки с числами - обман. Если у вашего списка есть какой-то уровень вложенности, то должны совпадать размерности у всех вложенных списков (подробнее про размерности поговорим позже):

In [6]:
some_other_data = [[1, 2], [3, 4], [5, 6, 7]]
some_other_tensor = torch.tensor(some_other_data)

some_other_tensor

ValueError: expected sequence of length 2 at dim 1 (got 3)

Также тензоры можно создавать из numpy массивов и наоборот:

In [7]:
some_numpy_array = np.array(some_data)

some_numpy_array

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [9]:
torch.tensor(some_numpy_array)

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

In [8]:
some_tensor_from_numpy = torch.from_numpy(some_numpy_array)

some_tensor_from_numpy

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

При этом если мы создаем тензор из numpy массива с помощью `torch.from_numpy`, то они делят между собой память, где лежат их данные и, соответственно, при изменении тензора меняется numpy массив и наоборот:

In [10]:
x = np.ones(10)
y = torch.from_numpy(x)

x, y

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64))

In [12]:
x += 1

x, y

(array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]),
 tensor([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.], dtype=torch.float64))

In [13]:
x = torch.ones(10)
y = x.numpy()

x, y

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [14]:
x += 1

x, y

(tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=float32))

Можем создать тензор со случайными или константными значениями:

In [15]:
shape = (2, 3)

random_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
empty_tensor = torch.empty(shape)

random_tensor, ones_tensor, zeros_tensor, empty_tensor

(tensor([[0.6187, 0.2395, 0.8571],
         [0.2679, 0.3852, 0.6423]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[4.5367e-41, 0.0000e+00, 5.0447e-44],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]))

In [16]:
torch.diag(torch.tensor([1, 2, 3]))

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

Теперь поговорим про размерности подробнее.

У тензора есть какой-то размер, какая форма. Первое с чем нужно определиться, какой **размерности** тензор - количество осей у него.

In [17]:
shape = (10)  # одна ось (вектор)

tensor = torch.rand(shape)

tensor

tensor([0.5294, 0.3790, 0.5040, 0.7912, 0.5307, 0.9942, 0.5493, 0.4817, 0.2963,
        0.4157])

In [18]:
shape = (2, 3)  # две оси (матрица)

tensor = torch.rand(shape)

tensor

tensor([[0.0235, 0.0931, 0.3083],
        [0.8078, 0.7678, 0.6935]])

In [19]:
shape = (3, 2, 3)  # три оси (и больше - тензор)

tensor = torch.rand(shape)

tensor

tensor([[[0.6493, 0.5683, 0.5937],
         [0.8001, 0.0361, 0.5763]],

        [[0.0855, 0.3761, 0.5679],
         [0.4451, 0.8539, 0.6284]],

        [[0.8667, 0.5331, 0.9322],
         [0.2881, 0.0390, 0.1777]]])

Тензор с размерностью 1 - это просто вектор, список чисел.

Тензор с размерностью 2 - это просто матрица, то есть список списков чисел.

Тензор с размерностью 3 и больше - это тензор, то есть список списков списков ... чисел.

Получить доступ к размеру уже созданного тензора - метод `.shape`:

In [20]:
some_data = [[[1], [2]], [[3], [4]], [[5], [6]]]
some_tensor = torch.tensor(some_data)

print(some_tensor)
print(some_tensor.shape)

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])
torch.Size([3, 2, 1])


In [21]:
torch.ones((3, 2, 1)).shape

torch.Size([3, 2, 1])

На первом семинаре по мо мы говорили про изображения, давайте сделаем тензор, который будет нам имитировать изображение - сделаем его размер `(c, h, w)`, где `h` и `w` это его высота и ширина, а `c` - число каналов в цветовом пространстве (в черно-белом 1, в RGB 3):

In [22]:
h = 9
w = 16
c = 3

shape = (c, h, w)

image_tensor = torch.rand(shape)

image_tensor

tensor([[[0.6173, 0.6204, 0.7245, 0.7032, 0.4962, 0.4095, 0.6284, 0.3591,
          0.5413, 0.5393, 0.8396, 0.4048, 0.3748, 0.3202, 0.4679, 0.6757],
         [0.3360, 0.5041, 0.1819, 0.8106, 0.6843, 0.9358, 0.4030, 0.0387,
          0.8144, 0.6670, 0.5364, 0.9210, 0.8167, 0.4983, 0.2885, 0.0953],
         [0.3634, 0.2332, 0.9528, 0.3374, 0.7775, 0.5109, 0.4956, 0.6988,
          0.6410, 0.7695, 0.8444, 0.0462, 0.6195, 0.4759, 0.5782, 0.2376],
         [0.1233, 0.4826, 0.2807, 0.7372, 0.1406, 0.1773, 0.4037, 0.1279,
          0.2918, 0.2858, 0.6302, 0.8487, 0.3111, 0.0434, 0.4731, 0.3027],
         [0.2983, 0.1499, 0.6127, 0.3746, 0.7864, 0.7386, 0.6956, 0.7785,
          0.6543, 0.9317, 0.2888, 0.6236, 0.2861, 0.9470, 0.2765, 0.3356],
         [0.4333, 0.3488, 0.7960, 0.1444, 0.1627, 0.4976, 0.6471, 0.4143,
          0.7065, 0.7118, 0.1303, 0.6294, 0.3948, 0.2642, 0.8172, 0.1242],
         [0.8808, 0.0135, 0.6844, 0.5903, 0.7071, 0.0259, 0.8222, 0.2282,
          0.0255, 0.4738, 0.4744

In [ ]:
image_tensor.shape

Можем попробовать поменять размер тензора, например, [вытянуть его в вектор](https://pytorch.org/docs/stable/generated/torch.ravel.html):

In [23]:
image_tensor.ravel()

tensor([0.6173, 0.6204, 0.7245, 0.7032, 0.4962, 0.4095, 0.6284, 0.3591, 0.5413,
        0.5393, 0.8396, 0.4048, 0.3748, 0.3202, 0.4679, 0.6757, 0.3360, 0.5041,
        0.1819, 0.8106, 0.6843, 0.9358, 0.4030, 0.0387, 0.8144, 0.6670, 0.5364,
        0.9210, 0.8167, 0.4983, 0.2885, 0.0953, 0.3634, 0.2332, 0.9528, 0.3374,
        0.7775, 0.5109, 0.4956, 0.6988, 0.6410, 0.7695, 0.8444, 0.0462, 0.6195,
        0.4759, 0.5782, 0.2376, 0.1233, 0.4826, 0.2807, 0.7372, 0.1406, 0.1773,
        0.4037, 0.1279, 0.2918, 0.2858, 0.6302, 0.8487, 0.3111, 0.0434, 0.4731,
        0.3027, 0.2983, 0.1499, 0.6127, 0.3746, 0.7864, 0.7386, 0.6956, 0.7785,
        0.6543, 0.9317, 0.2888, 0.6236, 0.2861, 0.9470, 0.2765, 0.3356, 0.4333,
        0.3488, 0.7960, 0.1444, 0.1627, 0.4976, 0.6471, 0.4143, 0.7065, 0.7118,
        0.1303, 0.6294, 0.3948, 0.2642, 0.8172, 0.1242, 0.8808, 0.0135, 0.6844,
        0.5903, 0.7071, 0.0259, 0.8222, 0.2282, 0.0255, 0.4738, 0.4744, 0.7568,
        0.1218, 0.6896, 0.6719, 0.2933, 

In [24]:
image_tensor.ravel().shape

torch.Size([432])

In [25]:
h * w * c

432

In [26]:
image_tensor.flatten()

tensor([0.6173, 0.6204, 0.7245, 0.7032, 0.4962, 0.4095, 0.6284, 0.3591, 0.5413,
        0.5393, 0.8396, 0.4048, 0.3748, 0.3202, 0.4679, 0.6757, 0.3360, 0.5041,
        0.1819, 0.8106, 0.6843, 0.9358, 0.4030, 0.0387, 0.8144, 0.6670, 0.5364,
        0.9210, 0.8167, 0.4983, 0.2885, 0.0953, 0.3634, 0.2332, 0.9528, 0.3374,
        0.7775, 0.5109, 0.4956, 0.6988, 0.6410, 0.7695, 0.8444, 0.0462, 0.6195,
        0.4759, 0.5782, 0.2376, 0.1233, 0.4826, 0.2807, 0.7372, 0.1406, 0.1773,
        0.4037, 0.1279, 0.2918, 0.2858, 0.6302, 0.8487, 0.3111, 0.0434, 0.4731,
        0.3027, 0.2983, 0.1499, 0.6127, 0.3746, 0.7864, 0.7386, 0.6956, 0.7785,
        0.6543, 0.9317, 0.2888, 0.6236, 0.2861, 0.9470, 0.2765, 0.3356, 0.4333,
        0.3488, 0.7960, 0.1444, 0.1627, 0.4976, 0.6471, 0.4143, 0.7065, 0.7118,
        0.1303, 0.6294, 0.3948, 0.2642, 0.8172, 0.1242, 0.8808, 0.0135, 0.6844,
        0.5903, 0.7071, 0.0259, 0.8222, 0.2282, 0.0255, 0.4738, 0.4744, 0.7568,
        0.1218, 0.6896, 0.6719, 0.2933, 

Посчитаем количество элементов в тензоре с помощью [специальной функции](https://pytorch.org/docs/stable/generated/torch.numel.html):

In [27]:
image_tensor.numel()

432

In [28]:
h = 2
w = 3
c = 3

shape = (c, h, w)

image_tensor = torch.rand(shape)

image_tensor

tensor([[[0.6835, 0.5969, 0.9521],
         [0.6092, 0.4818, 0.5859]],

        [[0.0879, 0.8525, 0.4099],
         [0.9246, 0.8976, 0.6821]],

        [[0.1486, 0.3753, 0.1593],
         [0.3865, 0.0848, 0.0642]]])

Попробуем поменять размер с помощью функции [reshape](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape):

In [29]:
image_tensor.reshape(c, h * w).shape

torch.Size([3, 6])

Попробуем собрать из нескольких тензоров один большой:

[torch.cat](https://pytorch.org/docs/stable/generated/torch.cat.html#torch.cat)

In [30]:
x = torch.randn(2, 3)

In [31]:
x

tensor([[-0.1935, -0.4720,  0.8311],
        [-0.6991,  0.0977,  1.4615]])

In [32]:
torch.cat((x, x, x), dim=0)

tensor([[-0.1935, -0.4720,  0.8311],
        [-0.6991,  0.0977,  1.4615],
        [-0.1935, -0.4720,  0.8311],
        [-0.6991,  0.0977,  1.4615],
        [-0.1935, -0.4720,  0.8311],
        [-0.6991,  0.0977,  1.4615]])

In [33]:
torch.cat((x, x, x), dim=1)

tensor([[-0.1935, -0.4720,  0.8311, -0.1935, -0.4720,  0.8311, -0.1935, -0.4720,
          0.8311],
        [-0.6991,  0.0977,  1.4615, -0.6991,  0.0977,  1.4615, -0.6991,  0.0977,
          1.4615]])

In [34]:
x = torch.randn(3, 3)
y = torch.randn(5, 3)
z = torch.randn(1, 3)

for tensor in [x, y, z]:
    print(tensor)

torch.cat((x, y, z), dim=0)

tensor([[-1.1929, -1.2555,  1.7683],
        [-1.2295, -1.1379,  0.5688],
        [-0.4710, -0.7888,  0.4556]])
tensor([[-0.4768, -0.9575, -0.6636],
        [-0.1527,  2.3403,  0.7375],
        [-1.0914,  0.1378,  0.3075],
        [-1.4908,  1.7797, -0.8095],
        [-1.8714,  0.9427,  0.2827]])
tensor([[ 0.1855, -0.0719, -0.5705]])


tensor([[-1.1929, -1.2555,  1.7683],
        [-1.2295, -1.1379,  0.5688],
        [-0.4710, -0.7888,  0.4556],
        [-0.4768, -0.9575, -0.6636],
        [-0.1527,  2.3403,  0.7375],
        [-1.0914,  0.1378,  0.3075],
        [-1.4908,  1.7797, -0.8095],
        [-1.8714,  0.9427,  0.2827],
        [ 0.1855, -0.0719, -0.5705]])

In [35]:
x = torch.randn(2, 3)
y = torch.randn(2, 5)
z = torch.randn(2, 1)

for tensor in [x, y, z]:
    print(tensor)

torch.cat((x, y, z), dim=1)

tensor([[1.4565, 0.3959, 0.1978],
        [0.7942, 0.4386, 3.4094]])
tensor([[-0.0947, -1.0935, -1.8605, -1.7235, -0.4713],
        [ 0.1355,  0.6774, -0.8234, -0.4280, -0.3726]])
tensor([[1.1001],
        [0.5586]])


tensor([[ 1.4565,  0.3959,  0.1978, -0.0947, -1.0935, -1.8605, -1.7235, -0.4713,
          1.1001],
        [ 0.7942,  0.4386,  3.4094,  0.1355,  0.6774, -0.8234, -0.4280, -0.3726,
          0.5586]])

Теперь добавим дополнительную ось:

[torch.unsqueeze](https://pytorch.org/docs/stable/generated/torch.unsqueeze.html)

In [36]:
x = torch.rand(2, 3)

print(x)
print()
print(x.unsqueeze(0), x.unsqueeze(0).shape)
print()
print(x.unsqueeze(1), x.unsqueeze(1).shape)
print()
print(x.unsqueeze(2), x.unsqueeze(2).shape)
print()
print(x.unsqueeze(2), x.unsqueeze(-1).shape)

tensor([[0.4081, 0.7041, 0.4633],
        [0.7767, 0.1353, 0.5465]])

tensor([[[0.4081, 0.7041, 0.4633],
         [0.7767, 0.1353, 0.5465]]]) torch.Size([1, 2, 3])

tensor([[[0.4081, 0.7041, 0.4633]],

        [[0.7767, 0.1353, 0.5465]]]) torch.Size([2, 1, 3])

tensor([[[0.4081],
         [0.7041],
         [0.4633]],

        [[0.7767],
         [0.1353],
         [0.5465]]]) torch.Size([2, 3, 1])

tensor([[[0.4081],
         [0.7041],
         [0.4633]],

        [[0.7767],
         [0.1353],
         [0.5465]]]) torch.Size([2, 3, 1])


Уберем лишние оси (где размер единичка):

In [37]:
x = torch.rand(1, 2, 1, 3)

print(x)
print()
print(x.squeeze(), x.squeeze().shape)
print()
print(x.squeeze(0), x.squeeze(0).shape)

tensor([[[[0.6061, 0.7466, 0.3964]],

         [[0.4814, 0.1354, 0.7523]]]])

tensor([[0.6061, 0.7466, 0.3964],
        [0.4814, 0.1354, 0.7523]]) torch.Size([2, 3])

tensor([[[0.6061, 0.7466, 0.3964]],

        [[0.4814, 0.1354, 0.7523]]]) torch.Size([2, 1, 3])


Теперь поговорим про типы данных в тензорах. По умолчанию в тензорах лежат числа в torch.float32 для вещественных и torch.int64 для целочисленных.

In [38]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9])

tensor

tensor([1.5000, 2.2000, 3.7000, 4.9000])

In [39]:
tensor.dtype

torch.float32

In [40]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9], dtype=torch.float16)

tensor

tensor([1.5000, 2.1992, 3.6992, 4.8984], dtype=torch.float16)

In [41]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9], dtype=torch.bfloat16)

tensor

tensor([1.5000, 2.2031, 3.7031, 4.9062], dtype=torch.bfloat16)

In [43]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9], dtype=torch.float64)

tensor

tensor([1.5000, 2.2000, 3.7000, 4.9000], dtype=torch.float64)

In [44]:
tensor = torch.tensor([15, 22, 37, 49])

tensor

tensor([15, 22, 37, 49])

In [45]:
tensor.dtype

torch.int64

In [46]:
tensor = torch.tensor([15, 22, 37, 49], dtype=torch.int32)

tensor

tensor([15, 22, 37, 49], dtype=torch.int32)

In [47]:
tensor = torch.tensor([15, 22, 37, 49], dtype=torch.int16)

tensor

tensor([15, 22, 37, 49], dtype=torch.int16)

Размещение тензора на GPU:

In [50]:
# !nvidia-smi

In [48]:
print(torch.cuda.is_available())
print(torch.cuda.get_device_name())

True
NVIDIA A100-SXM4-80GB


In [54]:
!nvidia-smi

Fri Oct 17 18:35:54 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.163.01             Driver Version: 550.163.01     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-80GB          Off |   00000000:82:00.0 Off |                    0 |
| N/A   77C    P0            472W /  500W |   65397MiB /  81920MiB |     96%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+-----

In [58]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

print(device)

cuda:0


In [61]:
tensor = torch.tensor([15, 22, 37, 49], device=device)

tensor

tensor([15, 22, 37, 49], device='cuda:0')

In [63]:
tensor = torch.tensor([15, 22, 37, 49])

print(tensor)

tensor = tensor.to(device)

tensor

tensor([15, 22, 37, 49])


tensor([15, 22, 37, 49], device='cuda:0')

In [64]:
tensor.to(torch.int32)

tensor([15, 22, 37, 49], device='cuda:0', dtype=torch.int32)

In [66]:
tensor = tensor.cpu()

tensor

tensor([15, 22, 37, 49])

In [67]:
tensor.cuda()

tensor([15, 22, 37, 49], device='cuda:6')

In [69]:
tensor.device

device(type='cpu')

In [74]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

a + b

tensor([[0.8409, 1.0787, 0.3875],
        [0.9969, 0.6892, 1.4277]])

In [75]:
a = a.to(device)

a + b

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [76]:
b = b.to(device)

a + b

tensor([[0.8409, 1.0787, 0.3875],
        [0.9969, 0.6892, 1.4277]], device='cuda:0')

### Операции с тензорами

Большая часть операций с тензорами хорошо описана в их [документации](https://pytorch.org/docs/stable/torch.html), разберем основные:

In [77]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

a, b

(tensor([[0.0309, 0.6722, 0.6042],
         [0.9942, 0.6476, 0.0447]]),
 tensor([[0.6253, 0.0154, 0.0480],
         [0.0244, 0.9261, 0.4814]]))

In [78]:
# поэлементные

print(a + b)

print()

print(torch.add(a, b))

print()

print(a.add(b))

tensor([[0.6562, 0.6876, 0.6522],
        [1.0186, 1.5737, 0.5261]])

tensor([[0.6562, 0.6876, 0.6522],
        [1.0186, 1.5737, 0.5261]])

tensor([[0.6562, 0.6876, 0.6522],
        [1.0186, 1.5737, 0.5261]])


In [79]:
print(a - b)

print()

print(torch.sub(a, b))

print()

print(a.sub(b))

tensor([[-0.5944,  0.6568,  0.5562],
        [ 0.9698, -0.2785, -0.4367]])

tensor([[-0.5944,  0.6568,  0.5562],
        [ 0.9698, -0.2785, -0.4367]])

tensor([[-0.5944,  0.6568,  0.5562],
        [ 0.9698, -0.2785, -0.4367]])


In [80]:
print(a * b)

print()

print(torch.mul(a, b))

print()

print(a.mul(b))

tensor([[0.0193, 0.0104, 0.0290],
        [0.0243, 0.5997, 0.0215]])

tensor([[0.0193, 0.0104, 0.0290],
        [0.0243, 0.5997, 0.0215]])

tensor([[0.0193, 0.0104, 0.0290],
        [0.0243, 0.5997, 0.0215]])


In [81]:
print(a / b)

print()

print(torch.div(a, b))

print()

print(a.div(b))

tensor([[ 0.0494, 43.5888, 12.5937],
        [40.7514,  0.6993,  0.0929]])

tensor([[ 0.0494, 43.5888, 12.5937],
        [40.7514,  0.6993,  0.0929]])

tensor([[ 0.0494, 43.5888, 12.5937],
        [40.7514,  0.6993,  0.0929]])


In [89]:
a = torch.rand(2, 3)
b = torch.rand(3, 4)
c = torch.rand(5, 5)

a, b, c

(tensor([[0.7605, 0.5782, 0.4993],
         [0.7083, 0.3239, 0.9818]]),
 tensor([[0.3765, 0.7187, 0.8230, 0.8691],
         [0.4340, 0.3239, 0.0973, 0.6674],
         [0.1120, 0.3731, 0.0032, 0.6584]]),
 tensor([[0.0105, 0.3037, 0.7841, 0.4561, 0.0245],
         [0.5982, 0.0032, 0.7877, 0.6420, 0.1092],
         [0.3925, 0.6777, 0.6403, 0.4500, 0.5647],
         [0.8848, 0.8183, 0.4197, 0.9401, 0.0820],
         [0.9480, 0.5417, 0.5558, 0.6933, 0.9678]]))

In [85]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

In [90]:
# матричные операции

print(a @ b, (a @ b).shape)

print()

print(torch.matmul(a, b), torch.matmul(a, b).shape)

print()

print(c.trace())

print()

print(c.exp())

tensor([[0.5932, 0.9202, 0.6838, 1.3756],
        [0.5172, 0.9803, 0.6176, 1.4782]]) torch.Size([2, 4])

tensor([[0.5932, 0.9202, 0.6838, 1.3756],
        [0.5172, 0.9803, 0.6176, 1.4782]]) torch.Size([2, 4])

tensor(2.5619)

tensor([[1.0105, 1.3549, 2.1904, 1.5779, 1.0248],
        [1.8189, 1.0032, 2.1983, 1.9003, 1.1153],
        [1.4807, 1.9694, 1.8971, 1.5683, 1.7590],
        [2.4224, 2.2667, 1.5215, 2.5603, 1.0855],
        [2.5807, 1.7190, 1.7433, 2.0003, 2.6321]])


### [Автоматическое дифференцирование](https://pytorch.org/docs/stable/notes/autograd.html)

In [134]:
x = torch.rand(5)

x

tensor([0.3399, 0.1397, 0.3930, 0.8000, 0.9079])

In [135]:
w = torch.rand(3, 5, requires_grad=True)

w

tensor([[0.0632, 0.5336, 0.3505, 0.6321, 0.6424],
        [0.9165, 0.4251, 0.1077, 0.7650, 0.6868],
        [0.9074, 0.7213, 0.9501, 0.5740, 0.8269]], requires_grad=True)

In [136]:
print(w.grad)

None


In [137]:
first_z = torch.empty(3)

first_z

tensor([2.2457e-28, 0.0000e+00, 2.2331e-28])

In [138]:
for i in range(3):
    first_z[i] = torch.sum(w[i] * x)

first_z

tensor([1.3227, 1.6488, 1.9925], grad_fn=<CopySlices>)

In [139]:
z = torch.matmul(x, w.t())

z

tensor([1.3227, 1.6488, 1.9925], grad_fn=<SqueezeBackward4>)

In [140]:
v = torch.rand(3, requires_grad=True)

v

tensor([0.7323, 0.2678, 0.6296], requires_grad=True)

In [141]:
print(v.grad)

None


In [142]:
y = torch.sum(z * v)

y

tensor(2.6648, grad_fn=<SumBackward0>)

In [152]:
w[0,0]

tensor(0.0632, grad_fn=<SelectBackward0>)

In [143]:
y.item()

2.664780616760254

In [144]:
loss = torch.mean((y - 2) ** 2)

In [145]:
loss

tensor(0.4419, grad_fn=<MeanBackward0>)

In [146]:
print(f'{x.grad=}\n')
print(f'{w.grad=}\n')
print(f'{z.grad=}\n')
print(f'{v.grad=}\n')

x.grad=None

w.grad=None

z.grad=None

v.grad=None



/var/tmp/ipykernel_2590428/162867685.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  print(f'{z.grad=}\n')


In [148]:
print(f'{x.grad=}\n')
print(f'{w.grad=}\n')
print(f'{z.grad=}\n')
print(f'{v.grad=}\n')

x.grad=None

w.grad=tensor([[0.3309, 0.1361, 0.3826, 0.7789, 0.8840],
        [0.1210, 0.0498, 0.1399, 0.2849, 0.3233],
        [0.2845, 0.1170, 0.3290, 0.6697, 0.7600]])

z.grad=None

v.grad=tensor([1.7587, 2.1921, 2.6491])



/var/tmp/ipykernel_2590428/162867685.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  print(f'{z.grad=}\n')


In [153]:
a = torch.rand(1, requires_grad=True)
b = torch.rand(1, requires_grad=True)

a, b

(tensor([0.9761], requires_grad=True), tensor([0.9873], requires_grad=True))

In [154]:
loss = (a - b)

loss

tensor([-0.0111], grad_fn=<SubBackward0>)

In [155]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [156]:
loss.backward()

In [157]:
print(f'{a.grad=}\n')  # 1
print(f'{b.grad=}\n')  # -1

a.grad=tensor([1.])

b.grad=tensor([-1.])



In [158]:
a.grad.zero_()
b.grad.zero_()

tensor([0.])

In [159]:
loss = (a - b) ** 2

loss

tensor([0.0001], grad_fn=<PowBackward0>)

In [160]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=tensor([0.])

b.grad=tensor([0.])



In [161]:
loss.backward()

In [162]:
print(f'{a.grad=}\n')  # 2 * (a - b)
print(f'{b.grad=}\n')  # -2 * (a - b)

a.grad=tensor([-0.0223])

b.grad=tensor([0.0223])



In [169]:
2 * (a - b)

tensor([[-0.5882,  1.0016,  0.9924,  1.2905, -1.4563],
        [-0.1035, -1.2224, -0.0171, -0.1647, -1.1635],
        [ 0.0918, -0.1194,  1.0468,  0.6607,  0.3615]], grad_fn=<MulBackward0>)

In [170]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=True)

a, b

(tensor([[0.5426, 0.0368, 0.1466, 0.2776, 0.4940],
         [0.0286, 0.3872, 0.1426, 0.4321, 0.7236],
         [0.1576, 0.4850, 0.2412, 0.3524, 0.7609]], requires_grad=True),
 tensor([[0.3885, 0.0855, 0.8605, 0.9241, 0.2711],
         [0.6470, 0.5867, 0.9039, 0.1510, 0.0100],
         [0.7816, 0.5447, 0.4061, 0.8495, 0.5218]], requires_grad=True))

In [171]:
loss = torch.mean(a * b)

loss

tensor(0.1573, grad_fn=<MeanBackward0>)

In [172]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [173]:
loss.backward()

In [174]:
print(f'{a.grad=}\n')  # b / (3 * 5)
print(f'{b.grad=}\n')  # a / (3 * 5)

a.grad=tensor([[0.0259, 0.0057, 0.0574, 0.0616, 0.0181],
        [0.0431, 0.0391, 0.0603, 0.0101, 0.0007],
        [0.0521, 0.0363, 0.0271, 0.0566, 0.0348]])

b.grad=tensor([[0.0362, 0.0025, 0.0098, 0.0185, 0.0329],
        [0.0019, 0.0258, 0.0095, 0.0288, 0.0482],
        [0.0105, 0.0323, 0.0161, 0.0235, 0.0507]])



In [175]:
a / 15

tensor([[0.0362, 0.0025, 0.0098, 0.0185, 0.0329],
        [0.0019, 0.0258, 0.0095, 0.0288, 0.0482],
        [0.0105, 0.0323, 0.0161, 0.0235, 0.0507]], grad_fn=<DivBackward0>)

In [176]:
b / 15

tensor([[0.0259, 0.0057, 0.0574, 0.0616, 0.0181],
        [0.0431, 0.0391, 0.0603, 0.0101, 0.0007],
        [0.0521, 0.0363, 0.0271, 0.0566, 0.0348]], grad_fn=<DivBackward0>)

In [177]:
a = torch.rand(3, 5, requires_grad=True)

print(f'{a=}\n')

loss1 = torch.sum(a ** 2) # 2a
loss2 = torch.sum(a) # 1

print(f'{a.grad=}\n')

loss1.backward()

print(f'{a.grad=}\n')

loss2.backward()

print(f'{a.grad=}\n')

a=tensor([[0.7178, 0.1453, 0.3178, 0.8704, 0.0754],
        [0.1022, 0.0981, 0.9522, 0.1077, 0.5394],
        [0.9669, 0.8639, 0.4065, 0.1005, 0.8290]], requires_grad=True)

a.grad=None

a.grad=tensor([[1.4356, 0.2906, 0.6357, 1.7407, 0.1507],
        [0.2044, 0.1963, 1.9043, 0.2153, 1.0787],
        [1.9339, 1.7278, 0.8130, 0.2011, 1.6580]])

a.grad=tensor([[2.4356, 1.2906, 1.6357, 2.7407, 1.1507],
        [1.2044, 1.1963, 2.9043, 1.2153, 2.0787],
        [2.9339, 2.7278, 1.8130, 1.2011, 2.6580]])



In [178]:
print(f'{2*a=}\n')
print(f'{2*a+1=}')

2*a=tensor([[1.4356, 0.2906, 0.6357, 1.7407, 0.1507],
        [0.2044, 0.1963, 1.9043, 0.2153, 1.0787],
        [1.9339, 1.7278, 0.8130, 0.2011, 1.6580]], grad_fn=<MulBackward0>)

2*a+1=tensor([[2.4356, 1.2906, 1.6357, 2.7407, 1.1507],
        [1.2044, 1.1963, 2.9043, 1.2153, 2.0787],
        [2.9339, 2.7278, 1.8130, 1.2011, 2.6580]], grad_fn=<AddBackward0>)


In [179]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=False)

a, b

(tensor([[9.0786e-01, 7.8189e-01, 7.8396e-01, 9.8992e-02, 1.7965e-04],
         [3.2895e-01, 1.9956e-01, 9.8841e-01, 5.3413e-02, 4.3164e-01],
         [4.2323e-01, 4.3647e-01, 3.0832e-01, 3.0479e-01, 4.1646e-01]],
        requires_grad=True),
 tensor([[0.6449, 0.9685, 0.8312, 0.7339, 0.8348],
         [0.4835, 0.6597, 0.1655, 0.8236, 0.3705],
         [0.2600, 0.1622, 0.7619, 0.3506, 0.4678]]))

In [180]:
loss = torch.sum(a - b)

loss

tensor(-2.0544, grad_fn=<SumBackward0>)

In [181]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [182]:
loss.backward()

In [183]:
print(f'{a.grad=}\n')  # all ones
print(f'{b.grad=}\n')  # None

a.grad=tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

b.grad=None



In [184]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=True)

a, b

(tensor([[0.8270, 0.9136, 0.5265, 0.0158, 0.6167],
         [0.5476, 0.6408, 0.0620, 0.0259, 0.5288],
         [0.5991, 0.7228, 0.1978, 0.5696, 0.1192]], requires_grad=True),
 tensor([[0.3163, 0.5877, 0.8124, 0.2254, 0.0077],
         [0.4663, 0.6403, 0.2285, 0.6014, 0.2294],
         [0.3249, 0.0678, 0.6864, 0.9622, 0.1503]], requires_grad=True))

In [185]:
with torch.no_grad():
    loss = torch.sum(a - b)

loss

tensor(0.6061)

In [186]:
loss = torch.sum(a - b)
loss

tensor(0.6061, grad_fn=<SumBackward0>)

In [187]:
loss

tensor(0.6061, grad_fn=<SumBackward0>)

In [188]:
loss.backward()

In [189]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=True)

a, b

(tensor([[3.0527e-01, 8.9479e-01, 1.4858e-01, 7.7968e-01, 5.4575e-02],
         [6.3801e-04, 4.2020e-01, 8.9232e-01, 8.9595e-01, 9.8183e-01],
         [8.7935e-01, 5.4213e-03, 8.3756e-01, 6.6405e-01, 7.6512e-01]],
        requires_grad=True),
 tensor([[0.5677, 0.0367, 0.5787, 0.1056, 0.9332],
         [0.5701, 0.0300, 0.1086, 0.4863, 0.7546],
         [0.6451, 0.7678, 0.4710, 0.4197, 0.6389]], requires_grad=True))

In [195]:
with torch.inference_mode():
    loss = torch.sum(a - b)

loss

tensor(1.4113)

In [193]:
with torch.no_grad():
    loss = torch.sum(a - b)

loss

tensor(1.4113)

In [196]:
loss.requires_grad = True

RuntimeError: Setting requires_grad=True on inference tensor outside InferenceMode is not allowed.

In [197]:
loss.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [198]:
with torch.no_grad():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)

    loss = torch.sum(a + b)

    print(f'{loss=}')

    loss.backward()

loss=tensor(14.6698)


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [199]:
a

tensor([[0.5401, 0.7122, 0.9269, 0.8732, 0.1738],
        [0.0771, 0.1903, 0.9471, 0.7204, 0.7863],
        [0.2187, 0.8073, 0.9264, 0.1342, 0.7220]], requires_grad=True)

In [200]:
loss2 = torch.sum(a + b)

loss2

tensor(14.6698, grad_fn=<SumBackward0>)

In [201]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [202]:
loss2.backward()

In [203]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

b.grad=tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])



In [204]:
with torch.inference_mode():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)

    loss = torch.sum(a + b)

    print(f'{loss=}')

    loss.backward()

loss=tensor(10.7882)


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [205]:
loss2 = torch.sum(a + b)

loss2

tensor(10.7882)

In [207]:
@torch.no_grad()
def foo():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)

    loss = torch.mean(a + b)

    print(f'{loss=}')

    return a, b

In [208]:
a, b = foo()

loss=tensor(0.9709)


In [209]:
torch.mean(a - b)

tensor(-0.2012, grad_fn=<MeanBackward0>)

In [210]:
@torch.inference_mode()
def foo():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)

    loss = torch.mean(a + b)

    print(f'{loss=}')

    return a, b

In [211]:
a, b = foo()

loss=tensor(1.0565)


In [212]:
torch.mean(a - b)

tensor(-0.0861)

In [213]:
a.requires_grad = False

## Полносвязные слои и функции активации в `PyTorch`

In [214]:
from torch import nn

In [215]:
import torch.nn as nn

### Полносвязный слой

>$y_j = \sum\limits_{i=1}^{n}x_iw_{ji} + b_j$


In [216]:
layer = nn.Linear(in_features=5, out_features=3)

In [217]:
layer

Linear(in_features=5, out_features=3, bias=True)

In [218]:
layer.weight

Parameter containing:
tensor([[-0.0336, -0.3298, -0.3811,  0.3935, -0.1224],
        [ 0.3735, -0.1159,  0.2462,  0.1783, -0.2171],
        [-0.4320,  0.3016,  0.2187,  0.2687,  0.4303]], requires_grad=True)

In [222]:
layer.weight.data

tensor([[-0.0336, -0.3298, -0.3811,  0.3935, -0.1224],
        [ 0.3735, -0.1159,  0.2462,  0.1783, -0.2171],
        [-0.4320,  0.3016,  0.2187,  0.2687,  0.4303]])

In [224]:
nn.Parameter(layer.weight.data, requires_grad=True)

Parameter containing:
tensor([[-0.0336, -0.3298, -0.3811,  0.3935, -0.1224],
        [ 0.3735, -0.1159,  0.2462,  0.1783, -0.2171],
        [-0.4320,  0.3016,  0.2187,  0.2687,  0.4303]], requires_grad=True)

In [219]:
layer.weight.shape

torch.Size([3, 5])

In [225]:
layer.bias

Parameter containing:
tensor([-0.2699,  0.3975,  0.2909], requires_grad=True)

In [226]:
layer.bias.shape

torch.Size([3])

In [227]:
layer = nn.Linear(in_features=5, out_features=3, bias=False)

In [228]:
layer.bias is None

True

In [230]:
layer.__call__

<bound method Module._wrapped_call_impl of Linear(in_features=5, out_features=3, bias=False)>

In [231]:
x = torch.randn(5)

print(layer(x))

tensor([-0.5016,  0.9495, -0.4001], grad_fn=<SqueezeBackward4>)


In [232]:
layer1 = nn.Linear(in_features=5, out_features=3)
layer2 = nn.Linear(in_features=3, out_features=1)

layer2(layer1(x))

tensor([0.6598], grad_fn=<ViewBackward0>)

### Функции активации

> Сигмоида $f(x) = \dfrac{1}{1 + e^{-x}}$

In [233]:
activation = nn.Sigmoid()

In [234]:
x = torch.randn(5)

print(x)

print(activation(x))

tensor([-1.1651, -0.4262,  0.3937, -0.9852, -1.0246])
tensor([0.2377, 0.3950, 0.5972, 0.2719, 0.2641])


> ReLU $f(x) = \max(0, x)$

In [235]:
activation = nn.ReLU()

In [236]:
x = torch.randn(5)

print(x)

print(activation(x))

tensor([ 0.4535, -0.7976,  0.9234,  1.5055, -1.4697])
tensor([0.4535, 0.0000, 0.9234, 1.5055, 0.0000])


> Leaky ReLU $f(x) = \max(0, x) + \alpha \min(0, x)$

In [237]:
activation = nn.LeakyReLU(negative_slope=0.001)

In [238]:
x = torch.randn(5)

print(x)

print(activation(x))

tensor([ 0.0149,  0.4748,  0.7398, -2.3925,  0.1441])
tensor([ 0.0149,  0.4748,  0.7398, -0.0024,  0.1441])


In [239]:
layer1 = nn.Linear(in_features=5, out_features=3)
activation = nn.LeakyReLU(negative_slope=0.001)
layer2 = nn.Linear(in_features=3, out_features=1)

layer2(activation(layer1(x)))

tensor([-0.5034], grad_fn=<ViewBackward0>)

## Градиентный спуск своими руками

In [ ]:
n_features = 2
n_objects = 300

torch.manual_seed(0)

w_true = torch.randn(n_features)
b_true = torch.randn(1)

x = (torch.rand(n_objects, n_features) - 0.5) * 10 * (torch.arange(n_features) * 2 + 1)
y = torch.matmul(x, w_true) + torch.randn(n_objects) + b_true

In [241]:
x.shape

torch.Size([300, 2])

In [242]:
y.shape

torch.Size([300])

In [243]:
n_steps = 200
step_size = 1e-2

In [247]:
w = torch.rand(n_features, requires_grad=True)
b = torch.rand(1, requires_grad=True)

for i in range(n_steps):
    y_pred = torch.matmul(x, w) + b

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 10 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

#     print(f'{w.grad=}\n')
#     print(f'{b.grad=}\n')

    with torch.no_grad():
        w -= w.grad * step_size
        b -= b.grad * step_size

    w.grad.zero_()
    b.grad.zero_()

MSE на шаге 1 15.86098
MSE на шаге 2 10.01271
MSE на шаге 3 7.67900
MSE на шаге 4 6.55727
MSE на шаге 5 5.90226
MSE на шаге 6 5.45731
MSE на шаге 7 5.12399
MSE на шаге 8 4.85846
MSE на шаге 9 4.63781
MSE на шаге 10 4.44852
MSE на шаге 11 4.28191
MSE на шаге 12 4.13220
MSE на шаге 13 3.99542
MSE на шаге 14 3.86883
MSE на шаге 15 3.75051
MSE на шаге 16 3.63907
MSE на шаге 17 3.53354
MSE на шаге 18 3.43320
MSE на шаге 19 3.33750
MSE на шаге 20 3.24605
MSE на шаге 21 3.15850
MSE на шаге 31 2.45568
MSE на шаге 41 1.98489
MSE на шаге 51 1.66876
MSE на шаге 61 1.45647
MSE на шаге 71 1.31391
MSE на шаге 81 1.21817
MSE на шаге 91 1.15388
MSE на шаге 101 1.11071
MSE на шаге 111 1.08172
MSE на шаге 121 1.06225
MSE на шаге 131 1.04918
MSE на шаге 141 1.04040
MSE на шаге 151 1.03450
MSE на шаге 161 1.03054
MSE на шаге 171 1.02788
MSE на шаге 181 1.02610
MSE на шаге 191 1.02490


In [ ]:
x.shape

In [252]:
layer = nn.Linear(in_features=n_features, out_features=1)



for i in range(n_steps):
    y_pred = layer(x)

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 10 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer.weight -= layer.weight.grad * step_size
        layer.bias -= layer.bias.grad * step_size

#     layer.weight.grad.zero_()
#     layer.bias.grad.zero_()

    layer.zero_grad()

MSE на шаге 1 37.76619
MSE на шаге 2 34.74113
MSE на шаге 3 33.09444
MSE на шаге 4 32.06023
MSE на шаге 5 31.34576
MSE на шаге 6 30.82119
MSE на шаге 7 30.41913
MSE на шаге 8 30.09991
MSE на шаге 9 29.83832
MSE на шаге 10 29.61762
MSE на шаге 11 29.42647
MSE на шаге 12 29.25710
MSE на шаге 13 29.10414
MSE на шаге 14 28.96386


KeyboardInterrupt: 

In [253]:
layer(x)

tensor([[-1.0576],
        [-0.9745],
        [-0.8925],
        [-1.0176],
        [-1.1166],
        [-0.9326],
        [-1.1587],
        [-1.1463],
        [-1.0290],
        [-0.8359],
        [-0.9656],
        [-1.1682],
        [-0.9279],
        [-0.8413],
        [-1.1682],
        [-1.0954],
        [-0.9153],
        [-0.8381],
        [-0.9182],
        [-1.1131],
        [-1.0044],
        [-1.1874],
        [-1.0319],
        [-0.8987],
        [-0.8668],
        [-0.9179],
        [-1.0803],
        [-1.0667],
        [-0.9836],
        [-1.0511],
        [-1.1813],
        [-0.9456],
        [-1.1583],
        [-1.1660],
        [-0.8496],
        [-0.8946],
        [-1.1750],
        [-0.8238],
        [-0.9775],
        [-0.9263],
        [-0.8993],
        [-1.0996],
        [-1.0740],
        [-0.8951],
        [-1.0449],
        [-0.9075],
        [-1.1277],
        [-0.9650],
        [-1.0099],
        [-0.8717],
        [-1.0366],
        [-1.1189],
        [-1.

In [254]:
layer(x).shape

torch.Size([300, 1])

In [255]:
x.shape

torch.Size([300, 2])

In [256]:
y.shape

torch.Size([300])

In [257]:
(layer(x) - y).shape

torch.Size([300, 300])

In [ ]:
layer(x).ravel().shape

In [ ]:
(layer(x).ravel() - y).shape

In [ ]:
layer = nn.Linear(in_features=n_features, out_features=1)

for i in range(n_steps):
    y_pred = layer(x).ravel()

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 10 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer.weight -= layer.weight.grad * step_size
        layer.bias -= layer.bias.grad * step_size

    layer.zero_grad()

In [ ]:
n_features = 5
n_objects = 300

torch.manual_seed(0)

w_true = torch.randn(n_features)

x = (torch.rand(n_objects, n_features) - 0.5) * 10 * (torch.arange(n_features) * 2 + 1)
y = torch.matmul(x, w_true) + torch.randn(n_objects)

In [ ]:
x.shape, y.shape

In [ ]:
n_steps = 500
step_size = 1e-3

In [ ]:
layer = nn.Linear(in_features=n_features, out_features=1)

for i in range(n_steps):
    y_pred = layer(x).ravel()

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 50 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer.weight -= layer.weight.grad * step_size
        layer.bias -= layer.bias.grad * step_size

    layer.zero_grad()

In [ ]:
n_steps = 1000
step_size = 3e-4

In [258]:
layer1 = nn.Linear(in_features=n_features, out_features=3)
layer2 = nn.Linear(in_features=3, out_features=1)
activation = nn.ReLU()


for i in range(n_steps):
    y_pred = layer2(activation(layer1(x))).ravel()

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 50 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer1.weight -= layer1.weight.grad * step_size
        layer1.bias -= layer1.bias.grad * step_size
        layer2.weight -= layer2.weight.grad * step_size
        layer2.bias -= layer2.bias.grad * step_size

    layer1.zero_grad()
    layer2.zero_grad()

MSE на шаге 1 31.55383
MSE на шаге 2 26.89486
MSE на шаге 3 21.14338
MSE на шаге 4 15.73163
MSE на шаге 5 13.05241
MSE на шаге 6 11.41121
MSE на шаге 7 9.83776
MSE на шаге 8 8.55517
MSE на шаге 9 7.55444
MSE на шаге 10 6.83588
MSE на шаге 11 6.37325
MSE на шаге 12 6.14436
MSE на шаге 13 6.02337
MSE на шаге 14 5.94775
MSE на шаге 15 5.90051
MSE на шаге 16 5.86855
MSE на шаге 17 5.84408
MSE на шаге 18 5.82453
MSE на шаге 19 5.80601
MSE на шаге 20 5.78766
MSE на шаге 51 5.30646
MSE на шаге 101 4.68867
MSE на шаге 151 4.48823
