# Введение. Полносвязные слои. Функции активации (ноутбук)

> Начнем осваивать библиотеку `PyTorch`.

## План ноутбука

1. Установка `PyTorch`
1. Введение в `PyTorch`
1. Полносвязные слои и функции активации в `PyTorch`
1. Градиентный спуск своими руками

## Установка `PyTorch`

Мы будем использовать библиотеку для глубинного обучения `PyTorch`, ее можно не устанавливать, можно пользоваться сайтами [Kaggle](kaggle.com) и [Google Colab](colab.research.google.com/) для обучения в облаке (или с учителем?).

Чтобы установить `PyTorch` локально себе на компьютер нужно ответить на два вопроса - какая у вас операционная система и есть ли у вас дискретная видеокарта (GPU) и если есть, то какого производителя. В зависимости от ваших ответов мы получаем три варианта по операционной системе - Linux, Mac и Windows; три варианта по дискретной видеокарте - нет видеокарты (доступен только центральный процессор CPU), есть видеокарта от Nvidia или есть видеокарта от AMD (это производитель именно чипа, конечный вендор может быть другой, например, ASUS, MSI, Palit). Работа с PyTorch с видеокартой от AMD это экзотика, которая выходит за рамки нашего курса, поэтому рассмотрим только варианты *нет видеокарты*/*есть видеокарта от Nvidia*.


Выберите на [сайте](https://pytorch.org/get-started/locally/) подходящие вам варианты операционной системы/видеокарты и скопируйте команду для установки. Разберем подробно самые популярные варианты установки:

### Установка в Linux ([поддерживаемые дистрибутивы](https://pytorch.org/get-started/locally/#supported-linux-distributions))

На линуксе будет работать поддержка `PyTorch` в любой конфигурации, что у вас нет видеокарты, что есть от Nvidia, что от AMD.

Пререквизит для работы с видеокартой от Nvidia - нужно поставить CUDA, это инструмент от компании Nvidia, который позволяет ускорять вычисления на их же ГПУ. Чтобы поставить себе на машину все правильно воспользуйтесь этим [гайдом](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html) от Nvidia.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu` для тех, у кого нет видеокарты.

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116` для тех, у кого есть видеокарта (либо другой `--extra-index-url`, смотрите на сайте PyTorch, в зависимости от версии CUDA).

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch` для тех, у кого нет видеокарты.

`conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge` для тех, у кого есть видеокарта (либо немного другая команда, в зависимости от версии CUDA).

### Установка в Windows

На винде будет работать поддержка `PyTorch` только для видеокарт от Nvidia и без видеокарт вообще.

Пререквизит для работы с видеокартой от Nvidia - нужно поставить CUDA, это инструмент от компании Nvidia, который позволяет ускорять вычисления на их же ГПУ. Чтобы поставить себе на машину все правильно воспользуйтесь этим [гайдом](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html) от Nvidia.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu` для тех, у кого нет видеокарты.

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116` для тех, у кого есть видеокарта (либо другой `--extra-index-url`, смотрите на сайте PyTorch, в зависимости от версии CUDA).

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch` для тех, у кого нет видеокарты.

`conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge` для тех, у кого есть видеокарта (либо немного другая команда, в зависимости от версии CUDA).



### Установка на Mac

На маках есть пока что поддержка `PyTorch` только центрального процессора, чуть позже появится поддержка ускорения на чипах M1, M2, M1 Pro и так далее.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu`

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch`

In [1]:
!nvidia-smi

Fri Oct 17 19:48:06 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.163.01             Driver Version: 550.163.01     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-80GB          Off |   00000000:82:00.0 Off |                    0 |
| N/A   43C    P0            168W /  500W |   34599MiB /  81920MiB |     50%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+-----

## Введение в `PyTorch`

### Тензоры

Тензоры — это специализированная структура данных, по сути это массивы и матрицы. Тензоры очень похожи на массивы в numpy, так что, если у вас хорошо с numpy, то разобраться в PyTorch тензорах будет очень просто. В PyTorch мы используем тензоры для кодирования входных и выходных данных модели, а также параметров модели.

In [2]:
import torch
import numpy as np

### Создание тензоров

Тензор можно создать напрямую из каких-то данных - нам подходят все списки с числами:

In [3]:
some_data = [1, 2, 3, 4]
some_tensor = torch.tensor(some_data)

some_tensor

tensor([1, 2, 3, 4])

In [4]:
some_data = [[1, 2], [3, 4], [5, 6]]
some_tensor = torch.tensor(some_data)

some_tensor

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [5]:
some_data = [[[1], [2]], [[3], [4]], [[5], [6]]]
some_tensor = torch.tensor(some_data)

some_tensor

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

На самом деле про "все" списки с числами - обман. Если у вашего списка есть какой-то уровень вложенности, то должны совпадать размерности у всех вложенных списков (подробнее про размерности поговорим позже):

In [6]:
some_other_data = [[1, 2], [3, 4], [5, 6, 7]]
some_other_tensor = torch.tensor(some_other_data)

some_other_tensor

ValueError: expected sequence of length 2 at dim 1 (got 3)

Также тензоры можно создавать из numpy массивов и наоборот:

In [7]:
some_numpy_array = np.array(some_data)

some_numpy_array

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [8]:
some_tensor_from_numpy = torch.tensor(some_numpy_array)

some_tensor_from_numpy

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

In [9]:
some_tensor_from_numpy = torch.from_numpy(some_numpy_array)

some_tensor_from_numpy

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

При этом если мы создаем тензор из numpy массива с помощью `torch.from_numpy`, то они делят между собой память, где лежат их данные и, соответственно, при изменении тензора меняется numpy массив и наоборот:

In [10]:
x = np.ones(10)
y = torch.from_numpy(x)

x, y

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64))

In [11]:
x += 1

x, y

(array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64))

In [12]:
x = torch.ones(10)
y = x.numpy()

x, y

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [13]:
x += 1

x, y

(tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=float32))

Можем создать тензор со случайными или константными значениями:

In [14]:
shape = (2, 3)

random_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
empty_tensor = torch.empty(shape)

random_tensor, ones_tensor, zeros_tensor, empty_tensor

(tensor([[0.2911, 0.0610, 0.2107],
         [0.0053, 0.8330, 0.0607]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[-2.8685e-02,  4.5730e-41, -2.8685e-02],
         [ 4.5730e-41,  4.4842e-44,  0.0000e+00]]))

In [15]:
torch.diag(torch.tensor([1, 2, 3]))

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

Теперь поговорим про размерности подробнее.

У тензора есть какой-то размер, какая форма. Первое с чем нужно определиться, какой **размерности** тензор - количество осей у него.

In [16]:
shape = (10)  # одна ось (вектор)

tensor = torch.rand(shape)

tensor

tensor([0.8608, 0.1747, 0.5505, 0.0042, 0.8825, 0.8070, 0.0050, 0.9078, 0.8223,
        0.9522])

In [17]:
shape = (2, 3)  # две оси (матрица)

tensor = torch.rand(shape)

tensor

tensor([[0.0782, 0.4977, 0.0872],
        [0.5849, 0.7266, 0.1825]])

In [18]:
shape = (3, 2, 3)  # три оси (и больше - тензор)

tensor = torch.rand(shape)

tensor

tensor([[[0.2459, 0.6725, 0.9758],
         [0.8015, 0.2459, 0.0141]],

        [[0.1817, 0.4007, 0.3740],
         [0.4980, 0.3281, 0.5341]],

        [[0.5520, 0.3573, 0.7722],
         [0.7608, 0.3856, 0.8808]]])

Тензор с размерностью 1 - это просто вектор, список чисел.

Тензор с размерностью 2 - это просто матрица, то есть список списков чисел.

Тензор с размерностью 3 и больше - это тензор, то есть список списков списков ... чисел.

Получить доступ к размеру уже созданного тензора - метод `.shape`:

In [19]:
some_data = [[[1], [2]], [[3], [4]], [[5], [6]]]
some_tensor = torch.tensor(some_data)

print(some_tensor)
print(some_tensor.shape)

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])
torch.Size([3, 2, 1])


In [20]:
torch.ones((3, 2, 1)).shape

torch.Size([3, 2, 1])

На первом семинаре по мо мы говорили про изображения, давайте сделаем тензор, который будет нам имитировать изображение - сделаем его размер `(c, h, w)`, где `h` и `w` это его высота и ширина, а `c` - число каналов в цветовом пространстве (в черно-белом 1, в RGB 3):

In [21]:
h = 9
w = 16
c = 3

shape = (c, h, w)

image_tensor = torch.rand(shape)

image_tensor

tensor([[[3.4834e-01, 2.7884e-02, 8.0684e-02, 7.5186e-01, 3.4362e-01,
          6.5246e-01, 4.8894e-01, 5.3870e-02, 8.8199e-01, 8.3450e-01,
          7.3133e-01, 5.3188e-01, 7.1405e-01, 2.8281e-01, 3.8194e-01,
          3.7774e-01],
         [8.3557e-01, 3.3941e-01, 5.6272e-01, 2.9753e-01, 3.2378e-01,
          1.1240e-01, 3.0590e-01, 9.4948e-01, 8.0090e-01, 1.5519e-01,
          2.7066e-01, 5.4093e-01, 8.2331e-02, 6.4418e-01, 2.0663e-01,
          5.0549e-01],
         [6.1464e-01, 6.5222e-01, 8.7434e-01, 3.6170e-01, 3.1538e-01,
          1.3968e-01, 8.9732e-01, 8.8469e-01, 5.8298e-01, 8.4492e-01,
          4.5564e-01, 3.9886e-01, 5.1061e-01, 4.3960e-01, 3.9460e-01,
          3.7583e-01],
         [5.9403e-01, 7.8491e-01, 1.5413e-01, 5.7784e-02, 7.0808e-02,
          8.1926e-01, 6.6567e-01, 7.9423e-01, 7.0491e-02, 1.9650e-01,
          1.1109e-01, 6.2597e-02, 7.3473e-01, 1.1500e-01, 3.8018e-02,
          8.6073e-01],
         [7.8879e-01, 3.9547e-02, 9.7794e-01, 3.1308e-01, 1.5483e-01

In [22]:
image_tensor.shape

torch.Size([3, 9, 16])

Можем попробовать поменять размер тензора, например, [вытянуть его в вектор](https://pytorch.org/docs/stable/generated/torch.ravel.html):

In [23]:
image_tensor.ravel()

tensor([3.4834e-01, 2.7884e-02, 8.0684e-02, 7.5186e-01, 3.4362e-01, 6.5246e-01,
        4.8894e-01, 5.3870e-02, 8.8199e-01, 8.3450e-01, 7.3133e-01, 5.3188e-01,
        7.1405e-01, 2.8281e-01, 3.8194e-01, 3.7774e-01, 8.3557e-01, 3.3941e-01,
        5.6272e-01, 2.9753e-01, 3.2378e-01, 1.1240e-01, 3.0590e-01, 9.4948e-01,
        8.0090e-01, 1.5519e-01, 2.7066e-01, 5.4093e-01, 8.2331e-02, 6.4418e-01,
        2.0663e-01, 5.0549e-01, 6.1464e-01, 6.5222e-01, 8.7434e-01, 3.6170e-01,
        3.1538e-01, 1.3968e-01, 8.9732e-01, 8.8469e-01, 5.8298e-01, 8.4492e-01,
        4.5564e-01, 3.9886e-01, 5.1061e-01, 4.3960e-01, 3.9460e-01, 3.7583e-01,
        5.9403e-01, 7.8491e-01, 1.5413e-01, 5.7784e-02, 7.0808e-02, 8.1926e-01,
        6.6567e-01, 7.9423e-01, 7.0491e-02, 1.9650e-01, 1.1109e-01, 6.2597e-02,
        7.3473e-01, 1.1500e-01, 3.8018e-02, 8.6073e-01, 7.8879e-01, 3.9547e-02,
        9.7794e-01, 3.1308e-01, 1.5483e-01, 6.8827e-01, 2.2541e-02, 7.3935e-01,
        1.3785e-01, 1.7345e-01, 5.2942e-

In [24]:
image_tensor.ravel().shape

torch.Size([432])

In [25]:
h * w * c

432

Посчитаем количество элементов в тензоре с помощью [специальной функции](https://pytorch.org/docs/stable/generated/torch.numel.html):

In [26]:
image_tensor.numel()

432

In [27]:
h = 2
w = 3
c = 3

shape = (c, h, w)

image_tensor = torch.rand(shape)

image_tensor

tensor([[[0.2468, 0.9357, 0.6560],
         [0.6227, 0.2050, 0.6671]],

        [[0.8631, 0.9016, 0.3896],
         [0.2286, 0.2027, 0.6695]],

        [[0.6516, 0.9168, 0.5204],
         [0.0331, 0.0926, 0.2427]]])

Попробуем поменять размер с помощью функции [reshape](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape):

In [28]:
image_tensor.reshape(c, h * w).shape

torch.Size([3, 6])

Попробуем собрать из нескольких тензоров один большой:

[torch.cat](https://pytorch.org/docs/stable/generated/torch.cat.html#torch.cat)

In [29]:
x = torch.randn(2, 3)

In [31]:
x

tensor([[-0.5248, -1.0931,  1.7343],
        [ 0.1405, -0.2430, -0.6954]])

In [32]:
torch.cat((x, x, x), dim=0)

tensor([[-0.5248, -1.0931,  1.7343],
        [ 0.1405, -0.2430, -0.6954],
        [-0.5248, -1.0931,  1.7343],
        [ 0.1405, -0.2430, -0.6954],
        [-0.5248, -1.0931,  1.7343],
        [ 0.1405, -0.2430, -0.6954]])

In [33]:
torch.cat((x, x, x), dim=1)

tensor([[-0.5248, -1.0931,  1.7343, -0.5248, -1.0931,  1.7343, -0.5248, -1.0931,
          1.7343],
        [ 0.1405, -0.2430, -0.6954,  0.1405, -0.2430, -0.6954,  0.1405, -0.2430,
         -0.6954]])

In [34]:
x = torch.randn(3, 3)
y = torch.randn(5, 3)
z = torch.randn(1, 3)

for tensor in [x, y, z]:
    print(tensor)

torch.cat((x, y, z), dim=0)

tensor([[ 1.0952, -1.1602, -0.3594],
        [-0.2264,  0.4544, -1.7354],
        [ 0.2350, -0.3612,  0.7982]])
tensor([[ 1.9280, -1.0093, -0.2413],
        [ 0.1175, -1.1828,  0.2210],
        [ 0.8373, -0.0704, -0.8808],
        [ 0.2483,  0.6145,  1.0912],
        [-0.5128,  0.0150,  2.6266]])
tensor([[-0.2160,  1.7405, -0.5530]])


tensor([[ 1.0952, -1.1602, -0.3594],
        [-0.2264,  0.4544, -1.7354],
        [ 0.2350, -0.3612,  0.7982],
        [ 1.9280, -1.0093, -0.2413],
        [ 0.1175, -1.1828,  0.2210],
        [ 0.8373, -0.0704, -0.8808],
        [ 0.2483,  0.6145,  1.0912],
        [-0.5128,  0.0150,  2.6266],
        [-0.2160,  1.7405, -0.5530]])

In [35]:
x = torch.randn(2, 3)
y = torch.randn(2, 5)
z = torch.randn(2, 1)

for tensor in [x, y, z]:
    print(tensor)

torch.cat((x, y, z), dim=1)

tensor([[-0.5979,  1.5756, -0.2311],
        [ 0.2106,  0.3154,  0.2257]])
tensor([[ 0.0519,  1.4533, -0.5218, -1.4615, -1.0723],
        [ 0.6099, -0.8938,  0.5712, -0.4585,  0.3912]])
tensor([[ 0.0469],
        [-0.2429]])


tensor([[-0.5979,  1.5756, -0.2311,  0.0519,  1.4533, -0.5218, -1.4615, -1.0723,
          0.0469],
        [ 0.2106,  0.3154,  0.2257,  0.6099, -0.8938,  0.5712, -0.4585,  0.3912,
         -0.2429]])

Теперь добавим дополнительную ось:

[torch.unsqueeze](https://pytorch.org/docs/stable/generated/torch.unsqueeze.html)

In [39]:
x = torch.rand(2, 3)

x.shape

torch.Size([2, 3])

In [41]:
img1 = torch.rand(16, 16, 3)

img2 = torch.rand(16, 16, 3)

In [42]:
img1.shape, img2.shape

(torch.Size([16, 16, 3]), torch.Size([16, 16, 3]))

In [45]:
torch.cat((img1, img2), dim=0).shape

torch.Size([32, 16, 3])

In [46]:
img1 = img1.unsqueeze(0)
img2 = img2.unsqueeze(0)

In [47]:
img1.shape, img2.shape

(torch.Size([1, 16, 16, 3]), torch.Size([1, 16, 16, 3]))

In [48]:
torch.cat((img1, img2), dim=0).shape

torch.Size([2, 16, 16, 3])

In [49]:
x = torch.rand(2, 3)

print(x)
print()
print(x.unsqueeze(0), x.unsqueeze(0).shape)
print()
print(x.unsqueeze(1), x.unsqueeze(1).shape)
print()
print(x.unsqueeze(2), x.unsqueeze(2).shape)
print()
print(x.unsqueeze(2), x.unsqueeze(-1).shape)

tensor([[0.2269, 0.0068, 0.2778],
        [0.2290, 0.1420, 0.7393]])

tensor([[[0.2269, 0.0068, 0.2778],
         [0.2290, 0.1420, 0.7393]]]) torch.Size([1, 2, 3])

tensor([[[0.2269, 0.0068, 0.2778]],

        [[0.2290, 0.1420, 0.7393]]]) torch.Size([2, 1, 3])

tensor([[[0.2269],
         [0.0068],
         [0.2778]],

        [[0.2290],
         [0.1420],
         [0.7393]]]) torch.Size([2, 3, 1])

tensor([[[0.2269],
         [0.0068],
         [0.2778]],

        [[0.2290],
         [0.1420],
         [0.7393]]]) torch.Size([2, 3, 1])


Уберем лишние оси (где размер единичка):

In [51]:
x = torch.rand(1, 2, 1, 3)

print(x)
print()
print(x.squeeze(), x.squeeze().shape)
print()
print(x.squeeze(0), x.squeeze(0).shape)

tensor([[[[0.7071, 0.8753, 0.5458]],

         [[0.0421, 0.6688, 0.2294]]]])

tensor([[0.7071, 0.8753, 0.5458],
        [0.0421, 0.6688, 0.2294]]) torch.Size([2, 3])

tensor([[[0.7071, 0.8753, 0.5458]],

        [[0.0421, 0.6688, 0.2294]]]) torch.Size([2, 1, 3])


Теперь поговорим про типы данных в тензорах. По умолчанию в тензорах лежат числа в torch.float32 для вещественных и torch.int64 для целочисленных.

In [52]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9])

tensor

tensor([1.5000, 2.2000, 3.7000, 4.9000])

In [53]:
tensor.dtype

torch.float32

In [54]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9], dtype=torch.float16)

tensor

tensor([1.5000, 2.1992, 3.6992, 4.8984], dtype=torch.float16)

In [55]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9], dtype=torch.bfloat16)

tensor

tensor([1.5000, 2.2031, 3.7031, 4.9062], dtype=torch.bfloat16)

In [56]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9], dtype=torch.float64)

tensor

tensor([1.5000, 2.2000, 3.7000, 4.9000], dtype=torch.float64)

In [57]:
tensor = torch.tensor([15, 22, 37, 49])

tensor

tensor([15, 22, 37, 49])

In [58]:
tensor.dtype

torch.int64

In [59]:
tensor = torch.tensor([15, 22, 37, 49], dtype=torch.int32)

tensor

tensor([15, 22, 37, 49], dtype=torch.int32)

In [60]:
tensor = torch.tensor([15, 22, 37, 49], dtype=torch.int16)

tensor

tensor([15, 22, 37, 49], dtype=torch.int16)

Размещение тензора на GPU:

In [61]:
print(torch.cuda.is_available())

True


In [62]:
print(torch.cuda.get_device_name())

NVIDIA A100-SXM4-80GB


In [63]:
print(torch.cuda.get_device_name(3))

NVIDIA A100-SXM4-80GB


In [64]:
!nvidia-smi

Fri Oct 17 20:04:20 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.163.01             Driver Version: 550.163.01     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-80GB          Off |   00000000:82:00.0 Off |                    0 |
| N/A   42C    P0            163W /  500W |   34599MiB /  81920MiB |     49%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+-----

In [65]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

print(device)

cuda:0


In [66]:
tensor = torch.tensor([15, 22, 37, 49], device=device)

tensor

tensor([15, 22, 37, 49], device='cuda:0')

In [67]:
tensor = torch.tensor([15, 22, 37, 49])

print(tensor)

tensor = tensor.to(device)

tensor

tensor([15, 22, 37, 49])


tensor([15, 22, 37, 49], device='cuda:0')

In [68]:
tensor.to(torch.int32)

tensor([15, 22, 37, 49], device='cuda:0', dtype=torch.int32)

In [71]:
tensor = tensor.cpu()

tensor

tensor([15, 22, 37, 49])

In [70]:
tensor.to(device)

tensor([15, 22, 37, 49], device='cuda:0')

In [74]:
tensor = tensor.cuda()

In [75]:
tensor.device

device(type='cuda', index=0)

In [76]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

a + b

tensor([[0.8653, 0.4230, 1.1089],
        [1.1523, 0.2986, 0.1058]])

In [77]:
a = a.to(device)

a + b

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [78]:
b = b.to(device)

a + b

tensor([[0.8653, 0.4230, 1.1089],
        [1.1523, 0.2986, 0.1058]], device='cuda:0')

### Операции с тензорами

Большая часть операций с тензорами хорошо описана в их [документации](https://pytorch.org/docs/stable/torch.html), разберем основные:

In [79]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

a, b

(tensor([[0.1770, 0.5925, 0.8391],
         [0.8871, 0.0059, 0.8675]]),
 tensor([[0.2369, 0.4864, 0.4682],
         [0.9381, 0.1952, 0.7330]]))

In [80]:
# поэлементные

print(a + b)

print()

print(torch.add(a, b))

print()

print(a.add(b))

tensor([[0.4139, 1.0789, 1.3073],
        [1.8252, 0.2011, 1.6005]])

tensor([[0.4139, 1.0789, 1.3073],
        [1.8252, 0.2011, 1.6005]])

tensor([[0.4139, 1.0789, 1.3073],
        [1.8252, 0.2011, 1.6005]])


In [81]:
print(a - b)

print()

print(torch.sub(a, b))

print()

print(a.sub(b))

tensor([[-0.0598,  0.1061,  0.3710],
        [-0.0510, -0.1894,  0.1345]])

tensor([[-0.0598,  0.1061,  0.3710],
        [-0.0510, -0.1894,  0.1345]])

tensor([[-0.0598,  0.1061,  0.3710],
        [-0.0510, -0.1894,  0.1345]])


In [82]:
print(a * b)

print()

print(torch.mul(a, b))

print()

print(a.mul(b))

tensor([[0.0419, 0.2882, 0.3928],
        [0.8322, 0.0011, 0.6358]])

tensor([[0.0419, 0.2882, 0.3928],
        [0.8322, 0.0011, 0.6358]])

tensor([[0.0419, 0.2882, 0.3928],
        [0.8322, 0.0011, 0.6358]])


In [83]:
print(a / b)

print()

print(torch.div(a, b))

print()

print(a.div(b))

tensor([[0.7474, 1.2182, 1.7924],
        [0.9456, 0.0301, 1.1835]])

tensor([[0.7474, 1.2182, 1.7924],
        [0.9456, 0.0301, 1.1835]])

tensor([[0.7474, 1.2182, 1.7924],
        [0.9456, 0.0301, 1.1835]])


In [84]:
a = torch.rand(2, 3)
b = torch.rand(3, 4)
c = torch.rand(5, 5)

a, b, c

(tensor([[0.5564, 0.8820, 0.6349],
         [0.7110, 0.9189, 0.7468]]),
 tensor([[0.9112, 0.7200, 0.7703, 0.5872],
         [0.7234, 0.5511, 0.4814, 0.5532],
         [0.6408, 0.4023, 0.6308, 0.7705]]),
 tensor([[0.9579, 0.4332, 0.1606, 0.0688, 0.1243],
         [0.8417, 0.3311, 0.2832, 0.1384, 0.1243],
         [0.3151, 0.6112, 0.8326, 0.0836, 0.9044],
         [0.4993, 0.0292, 0.0049, 0.1186, 0.9830],
         [0.7725, 0.0545, 0.3910, 0.6471, 0.7465]]))

In [85]:

print(a @ b, (a @ b).shape)

print()

tensor([[1.5519, 1.1421, 1.2536, 1.3038],
        [1.7911, 1.3187, 1.4610, 1.5011]]) torch.Size([2, 4])



In [86]:
print(torch.matmul(a, b), torch.matmul(a, b).shape)

print()

tensor([[1.5519, 1.1421, 1.2536, 1.3038],
        [1.7911, 1.3187, 1.4610, 1.5011]]) torch.Size([2, 4])



In [87]:
# матричные операции

print(c.trace())

print()

print(c.exp())

tensor(2.9866)

tensor([[2.6061, 1.5422, 1.1742, 1.0713, 1.1324],
        [2.3204, 1.3925, 1.3273, 1.1485, 1.1324],
        [1.3705, 1.8427, 2.2992, 1.0871, 2.4704],
        [1.6476, 1.0296, 1.0049, 1.1259, 2.6724],
        [2.1651, 1.0561, 1.4784, 1.9100, 2.1096]])


### [Автоматическое дифференцирование](https://pytorch.org/docs/stable/notes/autograd.html)

In [107]:
x = torch.rand(5)

x

tensor([0.1299, 0.8279, 0.0602, 0.9787, 0.9044])

In [108]:
w = torch.rand(3, 5, requires_grad=True)

w

tensor([[0.6401, 0.2118, 0.7658, 0.5868, 0.6202],
        [0.7012, 0.1825, 0.8870, 0.4691, 0.7435],
        [0.2150, 0.9924, 0.0870, 0.0658, 0.1154]], requires_grad=True)

In [109]:
print(w.grad)

None


In [110]:
first_z = torch.empty(3)

first_z

tensor([6.1029e-34, 0.0000e+00, 6.7339e-29])

In [111]:
for i in range(3):
    first_z[i] = torch.sum(w[i] * x)

first_z

tensor([1.4398, 1.4271, 1.0236], grad_fn=<CopySlices>)

In [112]:
z = torch.matmul(x, w.t())

z

tensor([1.4398, 1.4271, 1.0236], grad_fn=<SqueezeBackward4>)

In [113]:
v = torch.rand(3, requires_grad=True)

v

tensor([0.6825, 0.1598, 0.3828], requires_grad=True)

In [114]:
print(v.grad)

None


In [115]:
y = torch.sum(z * v)

y

tensor(1.6025, grad_fn=<SumBackward0>)

In [116]:
y.item()

1.6025211811065674

In [117]:
loss = torch.mean((y - 2) ** 2)

In [118]:
loss

tensor(0.1580, grad_fn=<MeanBackward0>)

In [119]:
print(f'{x.grad=}\n')
print(f'{w.grad=}\n')
print(f'{z=}\n')
print(f'{v.grad=}\n')

x.grad=None

w.grad=None

z=tensor([1.4398, 1.4271, 1.0236], grad_fn=<SqueezeBackward4>)

v.grad=None



In [120]:
loss.backward()

In [121]:
print(f'{x.grad=}\n')
print(f'{w.grad=}\n')
print(f'{z.grad=}\n')
print(f'{v.grad=}\n')

x.grad=None

w.grad=tensor([[-0.0705, -0.4492, -0.0327, -0.5310, -0.4907],
        [-0.0165, -0.1051, -0.0077, -0.1243, -0.1149],
        [-0.0395, -0.2520, -0.0183, -0.2979, -0.2752]])

z.grad=None

v.grad=tensor([-1.1446, -1.1345, -0.8137])



/var/tmp/ipykernel_2410344/162867685.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  print(f'{z.grad=}\n')


In [122]:
a = torch.rand(1, requires_grad=True)
b = torch.rand(1, requires_grad=True)

a, b

(tensor([0.5423], requires_grad=True), tensor([0.2466], requires_grad=True))

In [123]:
loss = (a - b)

loss

tensor([0.2957], grad_fn=<SubBackward0>)

In [124]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [125]:
loss.backward()

In [126]:
print(f'{a.grad=}\n')  # 1
print(f'{b.grad=}\n')  # -1

a.grad=tensor([1.])

b.grad=tensor([-1.])



In [127]:
a.grad.zero_()
b.grad.zero_()

tensor([0.])

In [128]:
loss = (a - b) ** 2

loss

tensor([0.0874], grad_fn=<PowBackward0>)

In [129]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=tensor([0.])

b.grad=tensor([0.])



In [130]:
loss.backward()

In [131]:
print(f'{a.grad=}\n')  # 2 * (a - b)
print(f'{b.grad=}\n')  # -2 * (a - b)

a.grad=tensor([0.5914])

b.grad=tensor([-0.5914])



In [132]:
2 * (a - b)

tensor([0.5914], grad_fn=<MulBackward0>)

In [133]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=True)

a, b

(tensor([[0.5827, 0.8224, 0.8522, 0.9378, 0.5499],
         [0.3480, 0.8043, 0.0666, 0.7338, 0.0635],
         [0.0173, 0.9878, 0.3809, 0.9813, 0.7320]], requires_grad=True),
 tensor([[0.5484, 0.3701, 0.2232, 0.6187, 0.5472],
         [0.5894, 0.9985, 0.2056, 0.6656, 0.0074],
         [0.7365, 0.0966, 0.5076, 0.8114, 0.0602]], requires_grad=True))

In [134]:
loss = torch.mean(a * b)

loss

tensor(0.2898, grad_fn=<MeanBackward0>)

In [135]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [136]:
loss.backward()

In [138]:
print(f'{a.grad=}\n')  # b / (3 * 5)
print(f'{b.grad=}\n')  # a / (3 * 5)

a.grad=tensor([[0.0366, 0.0247, 0.0149, 0.0412, 0.0365],
        [0.0393, 0.0666, 0.0137, 0.0444, 0.0005],
        [0.0491, 0.0064, 0.0338, 0.0541, 0.0040]])

b.grad=tensor([[0.0388, 0.0548, 0.0568, 0.0625, 0.0367],
        [0.0232, 0.0536, 0.0044, 0.0489, 0.0042],
        [0.0012, 0.0659, 0.0254, 0.0654, 0.0488]])



In [139]:
a / 15

tensor([[0.0388, 0.0548, 0.0568, 0.0625, 0.0367],
        [0.0232, 0.0536, 0.0044, 0.0489, 0.0042],
        [0.0012, 0.0659, 0.0254, 0.0654, 0.0488]], grad_fn=<DivBackward0>)

In [140]:
b / 15

tensor([[0.0366, 0.0247, 0.0149, 0.0412, 0.0365],
        [0.0393, 0.0666, 0.0137, 0.0444, 0.0005],
        [0.0491, 0.0064, 0.0338, 0.0541, 0.0040]], grad_fn=<DivBackward0>)

In [141]:
a = torch.rand(3, 5, requires_grad=True)

print(f'{a=}\n')

loss1 = torch.sum(a ** 2) # 2a
loss2 = torch.sum(a) # 1

print(f'{a.grad=}\n')

loss1.backward()

print(f'{a.grad=}\n')

loss2.backward()

print(f'{a.grad=}\n')

a=tensor([[0.2526, 0.0941, 0.7234, 0.4883, 0.0487],
        [0.2842, 0.8598, 0.2982, 0.3678, 0.6317],
        [0.5803, 0.3851, 0.6289, 0.8962, 0.4969]], requires_grad=True)

a.grad=None

a.grad=tensor([[0.5052, 0.1882, 1.4469, 0.9767, 0.0974],
        [0.5684, 1.7196, 0.5964, 0.7356, 1.2635],
        [1.1605, 0.7702, 1.2577, 1.7924, 0.9939]])

a.grad=tensor([[1.5052, 1.1882, 2.4469, 1.9767, 1.0974],
        [1.5684, 2.7196, 1.5964, 1.7356, 2.2635],
        [2.1605, 1.7702, 2.2577, 2.7924, 1.9939]])



In [142]:
print(f'{2*a=}\n')
print(f'{2*a+1=}')

2*a=tensor([[0.5052, 0.1882, 1.4469, 0.9767, 0.0974],
        [0.5684, 1.7196, 0.5964, 0.7356, 1.2635],
        [1.1605, 0.7702, 1.2577, 1.7924, 0.9939]], grad_fn=<MulBackward0>)

2*a+1=tensor([[1.5052, 1.1882, 2.4469, 1.9767, 1.0974],
        [1.5684, 2.7196, 1.5964, 1.7356, 2.2635],
        [2.1605, 1.7702, 2.2577, 2.7924, 1.9939]], grad_fn=<AddBackward0>)


In [143]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=False)

a, b

(tensor([[0.4937, 0.0845, 0.0194, 0.4042, 0.5292],
         [0.1017, 0.6406, 0.4870, 0.4796, 0.8632],
         [0.5621, 0.8540, 0.9317, 0.8477, 0.7745]], requires_grad=True),
 tensor([[0.6524, 0.5915, 0.6218, 0.6237, 0.5548],
         [0.2515, 0.6582, 0.4726, 0.3427, 0.6731],
         [0.2883, 0.3034, 0.8570, 0.1767, 0.4269]]))

In [144]:
loss = torch.sum(a - b)

loss

tensor(0.5783, grad_fn=<SumBackward0>)

In [145]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [146]:
loss.backward()

In [147]:
print(f'{a.grad=}\n')  # all ones
print(f'{b.grad=}\n')  # None

a.grad=tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

b.grad=None



In [148]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=True)

a, b

(tensor([[0.6345, 0.3786, 0.5147, 0.0290, 0.9986],
         [0.5708, 0.1237, 0.6492, 0.4243, 0.6805],
         [0.5683, 0.8320, 0.2339, 0.8101, 0.5310]], requires_grad=True),
 tensor([[0.0473, 0.3011, 0.6636, 0.1944, 0.7070],
         [0.5378, 0.1624, 0.6578, 0.5796, 0.5400],
         [0.3686, 0.3467, 0.1496, 0.4406, 0.9235]], requires_grad=True))

In [149]:
loss = torch.sum(a - b)

In [150]:
loss.backward()

In [151]:
print(f'{a.grad=}\n')  # all ones
print(f'{b.grad=}\n')  # None

a.grad=tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

b.grad=tensor([[-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.]])



In [152]:
a = torch.rand(3, 5, requires_grad=True)
b = torch.rand(3, 5, requires_grad=True)

a, b

(tensor([[0.1300, 0.6826, 0.5671, 0.5036, 0.7779],
         [0.8717, 0.3148, 0.4143, 0.7689, 0.2729],
         [0.3649, 0.0072, 0.4425, 0.7963, 0.4902]], requires_grad=True),
 tensor([[0.2565, 0.0327, 0.3387, 0.6098, 0.7989],
         [0.1290, 0.8134, 0.9779, 0.3097, 0.6338],
         [0.2177, 0.3886, 0.9503, 0.5584, 0.0344]], requires_grad=True))

In [155]:
with torch.inference_mode():
    loss = torch.sum(a - b)

loss

tensor(0.3548)

In [156]:
loss.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [157]:
with torch.no_grad():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)

    loss = torch.sum(a + b)

    print(f'{loss=}')

    loss.backward()

loss=tensor(14.3149)


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [158]:
a, b

(tensor([[0.9432, 0.5385, 0.0869, 0.1241, 0.4252],
         [0.4901, 0.7618, 0.2504, 0.3490, 0.0618],
         [0.6637, 0.6686, 0.3445, 0.9468, 0.7535]], requires_grad=True),
 tensor([[0.6082, 0.5065, 0.4687, 0.3199, 0.9082],
         [0.8384, 0.2575, 0.6644, 0.1150, 0.5089],
         [0.1262, 0.0676, 0.7918, 0.5565, 0.1691]], requires_grad=True))

In [159]:
loss2 = torch.sum(a + b)

loss2

tensor(14.3149, grad_fn=<SumBackward0>)

In [160]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=None

b.grad=None



In [161]:
loss2.backward()

In [162]:
print(f'{a.grad=}\n')
print(f'{b.grad=}\n')

a.grad=tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

b.grad=tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])



In [163]:
with torch.inference_mode():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)

    loss = torch.sum(a + b)

    print(f'{loss=}')

    loss.backward()

loss=tensor(17.5137)


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [164]:
loss2 = torch.sum(a + b)

loss2

tensor(17.5137)

In [165]:
@torch.no_grad()
def foo():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)

    loss = torch.mean(a + b)

    print(f'{loss=}')

    return a, b, loss

In [166]:
a, b, loss = foo()

loss=tensor(1.0004)


In [167]:
loss.requires_grad = True

In [168]:
loss.backward()

In [169]:
print(a.grad, b.grad)

None None


In [170]:
@torch.inference_mode()
def foo():
    a = torch.rand(3, 5, requires_grad=True)
    b = torch.rand(3, 5, requires_grad=True)

    loss = torch.mean(a + b)

    print(f'{loss=}')

    return a, b, loss

In [171]:
a, b, loss = foo()

loss=tensor(1.0268)


In [172]:
loss.requires_grad = True

RuntimeError: Setting requires_grad=True on inference tensor outside InferenceMode is not allowed.

In [173]:
loss.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

## Полносвязные слои и функции активации в `PyTorch`

In [174]:
from torch import nn

In [175]:
import torch.nn as nn

### Полносвязный слой

>$y_j = \sum\limits_{i=1}^{n}x_iw_{ji} + b_j$


In [176]:
layer = nn.Linear(in_features=5, out_features=3)

In [177]:
layer

Linear(in_features=5, out_features=3, bias=True)

In [178]:
layer.weight

Parameter containing:
tensor([[ 0.0817,  0.2092,  0.3020, -0.2634,  0.2730],
        [ 0.0932, -0.1603,  0.1604,  0.2038,  0.1870],
        [-0.3313, -0.4024, -0.0394, -0.2524, -0.1378]], requires_grad=True)

In [179]:
layer.weight.shape

torch.Size([3, 5])

In [180]:
layer.bias

Parameter containing:
tensor([-0.4185,  0.0215, -0.2166], requires_grad=True)

In [181]:
layer.bias.shape

torch.Size([3])

In [182]:
layer = nn.Linear(in_features=5, out_features=3, bias=False)

In [183]:
layer.bias is None

True

In [184]:
x = torch.randn(5)

print(layer(x))

tensor([-0.1656,  1.1688, -0.4705], grad_fn=<SqueezeBackward4>)


In [185]:
layer1 = nn.Linear(in_features=5, out_features=3)
layer2 = nn.Linear(in_features=3, out_features=1)

layer2(layer1(x))

tensor([1.0197], grad_fn=<ViewBackward0>)

### Функции активации

> Сигмоида $f(x) = \dfrac{1}{1 + e^{-x}}$

In [186]:
activation = nn.Sigmoid()

In [187]:
x = torch.randn(5)

print(x)

print(activation(x))

tensor([-0.3451,  0.6429,  1.3197,  2.5507, -0.4774])
tensor([0.4146, 0.6554, 0.7891, 0.9276, 0.3829])


> ReLU $f(x) = \max(0, x)$

In [188]:
activation = nn.ReLU()

In [191]:
x = torch.randn(5)

print(x)

print(activation(x))

tensor([-1.0428, -0.6797, -1.3791,  0.2758,  1.2632])
tensor([0.0000, 0.0000, 0.0000, 0.2758, 1.2632])


> Leaky ReLU $f(x) = \max(0, x) + \alpha \min(0, x)$

In [192]:
activation = nn.LeakyReLU(negative_slope=0.001)

In [193]:
x = torch.randn(5)

print(x)

print(activation(x))

tensor([ 0.4153,  1.6486,  0.0228, -0.5279,  0.9366])
tensor([ 4.1529e-01,  1.6486e+00,  2.2817e-02, -5.2790e-04,  9.3658e-01])


In [194]:
layer1 = nn.Linear(in_features=5, out_features=3)
activation = nn.LeakyReLU(negative_slope=0.001)
layer2 = nn.Linear(in_features=3, out_features=1)

layer2(activation(layer1(x)))

tensor([0.0524], grad_fn=<ViewBackward0>)

## Градиентный спуск своими руками

In [195]:
n_features = 2
n_objects = 300

torch.manual_seed(0)

w_true = torch.randn(n_features)
b_true = torch.randn(1)

x = (torch.rand(n_objects, n_features) - 0.5) * 10 * (torch.arange(n_features) * 2 + 1)
y = torch.matmul(x, w_true) + torch.randn(n_objects) + b_true

In [196]:
x.shape, y.shape

(torch.Size([300, 2]), torch.Size([300]))

In [197]:
n_steps = 200
step_size = 1e-2

In [198]:
w = torch.rand(n_features, requires_grad=True)
b = torch.rand(1, requires_grad=True)

for i in range(n_steps):
    y_pred = torch.matmul(x, w) + b

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 10 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

#     print(f'{w.grad=}\n')
#     print(f'{b.grad=}\n')

    with torch.no_grad():
        w -= w.grad * step_size
        b -= b.grad * step_size

    w.grad.zero_()
    b.grad.zero_()

MSE на шаге 1 23.65750
MSE на шаге 2 15.53605
MSE на шаге 3 12.11575
MSE на шаге 4 10.36995
MSE на шаге 5 9.30175
MSE на шаге 6 8.55659
MSE на шаге 7 7.99169
MSE на шаге 8 7.53972
MSE на шаге 9 7.16377
MSE на шаге 10 6.84131
MSE на шаге 11 6.55765
MSE на шаге 12 6.30292
MSE на шаге 13 6.07033
MSE на шаге 14 5.85515
MSE на шаге 15 5.65409
MSE на шаге 16 5.46479
MSE на шаге 17 5.28555
MSE на шаге 18 5.11514
MSE на шаге 19 4.95265
MSE на шаге 20 4.79735
MSE на шаге 21 4.64871
MSE на шаге 31 3.45555
MSE на шаге 41 2.65631
MSE на шаге 51 2.11964
MSE на шаге 61 1.75925
MSE на шаге 71 1.51724
MSE на шаге 81 1.35471
MSE на шаге 91 1.24558
MSE на шаге 101 1.17229
MSE на шаге 111 1.12307
MSE на шаге 121 1.09002
MSE на шаге 131 1.06782
MSE на шаге 141 1.05292
MSE на шаге 151 1.04291
MSE на шаге 161 1.03619
MSE на шаге 171 1.03168
MSE на шаге 181 1.02864
MSE на шаге 191 1.02661


In [199]:
layer = nn.Linear(in_features=n_features, out_features=1)

for i in range(n_steps):
    y_pred = layer(x).ravel()

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 10 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer.weight -= layer.weight.grad * step_size
        layer.bias -= layer.bias.grad * step_size

    layer.zero_grad()

MSE на шаге 1 94.84772
MSE на шаге 2 49.19622
MSE на шаге 3 30.07972
MSE на шаге 4 20.65595
MSE на шаге 5 15.28455
MSE на шаге 6 11.90099
MSE на шаге 7 9.63998
MSE на шаге 8 8.07625
MSE на шаге 9 6.96954
MSE на шаге 10 6.17078
MSE на шаге 11 5.58258
MSE на шаге 12 5.13959
MSE на шаге 13 4.79746
MSE на шаге 14 4.52587
MSE на шаге 15 4.30402
MSE на шаге 16 4.11764
MSE на шаге 17 3.95690
MSE на шаге 18 3.81501
MSE на шаге 19 3.68727
MSE на шаге 20 3.57042
MSE на шаге 21 3.46217
MSE на шаге 31 2.64666
MSE на шаге 41 2.11284
MSE на шаге 51 1.75468
MSE на шаге 61 1.51416
MSE на шаге 71 1.35265
MSE на шаге 81 1.24419
MSE на шаге 91 1.17136
MSE на шаге 101 1.12244
MSE на шаге 111 1.08960
MSE на шаге 121 1.06754
MSE на шаге 131 1.05273
MSE на шаге 141 1.04278
MSE на шаге 151 1.03610
MSE на шаге 161 1.03162
MSE на шаге 171 1.02861
MSE на шаге 181 1.02658
MSE на шаге 191 1.02522


In [200]:
n_features = 5
n_objects = 300

torch.manual_seed(0)

w_true = torch.randn(n_features)

x = (torch.rand(n_objects, n_features) - 0.5) * 10 * (torch.arange(n_features) * 2 + 1)
y = torch.matmul(x, w_true) + torch.randn(n_objects)

In [201]:
x.shape, y.shape

(torch.Size([300, 5]), torch.Size([300]))

In [202]:
n_steps = 500
step_size = 1e-3

In [203]:
layer = nn.Linear(in_features=n_features, out_features=1)

for i in range(n_steps):
    y_pred = layer(x).ravel()

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 50 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer.weight -= layer.weight.grad * step_size
        layer.bias -= layer.bias.grad * step_size

    layer.zero_grad()

MSE на шаге 1 1522.64282
MSE на шаге 2 345.22870
MSE на шаге 3 134.71320
MSE на шаге 4 69.14159
MSE на шаге 5 45.61798
MSE на шаге 6 36.15923
MSE на шаге 7 31.74179
MSE на шаге 8 29.24492
MSE на шаге 9 27.53952
MSE на шаге 10 26.19924
MSE на шаге 11 25.05364
MSE на шаге 12 24.02866
MSE на шаге 13 23.08827
MSE на шаге 14 22.21260
MSE на шаге 15 21.38941
MSE на шаге 16 20.61047
MSE на шаге 17 19.86992
MSE на шаге 18 19.16344
MSE на шаге 19 18.48770
MSE на шаге 20 17.84015
MSE на шаге 51 6.27402
MSE на шаге 101 1.74083
MSE на шаге 151 1.02593
MSE на шаге 201 0.91269
MSE на шаге 251 0.89435
MSE на шаге 301 0.89104
MSE на шаге 351 0.89019
MSE на шаге 401 0.88977
MSE на шаге 451 0.88948


In [204]:
n_steps = 1000
step_size = 3e-4

In [205]:
layer1 = nn.Linear(in_features=n_features, out_features=3)
layer2 = nn.Linear(in_features=3, out_features=1)
activation = nn.ReLU()


for i in range(n_steps):
    y_pred = layer2(activation(layer1(x))).ravel()

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 50 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer1.weight -= layer1.weight.grad * step_size
        layer1.bias -= layer1.bias.grad * step_size
        layer2.weight -= layer2.weight.grad * step_size
        layer2.bias -= layer2.bias.grad * step_size

    layer1.zero_grad()
    layer2.zero_grad()

MSE на шаге 1 2065.53369
MSE на шаге 2 1941.40039
MSE на шаге 3 1890.73816
MSE на шаге 4 1863.17334
MSE на шаге 5 1843.74536
MSE на шаге 6 1825.21838
MSE на шаге 7 1803.15234
MSE на шаге 8 1775.96960
MSE на шаге 9 1741.44421
MSE на шаге 10 1696.50024
MSE на шаге 11 1638.66479
MSE на шаге 12 1570.60828
MSE на шаге 13 1498.17651
MSE на шаге 14 1426.69543
MSE на шаге 15 1361.06189
MSE на шаге 16 1304.04346
MSE на шаге 17 1252.44177
MSE на шаге 18 1201.12524
MSE на шаге 19 1142.44934
MSE на шаге 20 1069.69458
MSE на шаге 51 10.77816
MSE на шаге 101 5.31390
MSE на шаге 151 3.22006
MSE на шаге 201 2.08226
MSE на шаге 251 1.45981
MSE на шаге 301 1.16964
MSE на шаге 351 1.03444
MSE на шаге 401 0.97123


KeyboardInterrupt: 

In [207]:
n_features = 5
n_objects = 300

torch.manual_seed(0)

w_true = torch.randn(n_features).to(device)

x = (torch.rand(n_objects, n_features).to(device) - 0.5) * 10 * (torch.arange(n_features).to(device) * 2 + 1).to(device)
y = torch.matmul(x, w_true) + torch.randn(n_objects).to(device)

In [208]:
layer1 = nn.Linear(in_features=n_features, out_features=3).to(device)
layer2 = nn.Linear(in_features=3, out_features=1).to(device)
activation = nn.ReLU().to(device)


for i in range(n_steps):
    y_pred = layer2(activation(layer1(x))).ravel()

    mse = torch.mean((y_pred - y) ** 2)

    if i < 20 or i % 50 == 0:
        print(f'MSE на шаге {i + 1} {mse.item():.5f}')

    mse.backward()

    with torch.no_grad():
        layer1.weight -= layer1.weight.grad * step_size
        layer1.bias -= layer1.bias.grad * step_size
        layer2.weight -= layer2.weight.grad * step_size
        layer2.bias -= layer2.bias.grad * step_size

    layer1.zero_grad()
    layer2.zero_grad()

MSE на шаге 1 1807.96228
MSE на шаге 2 1708.97791
MSE на шаге 3 1626.73584
MSE на шаге 4 1537.59045
MSE на шаге 5 1444.65527
MSE на шаге 6 1356.95361
MSE на шаге 7 1281.51331
MSE на шаге 8 1223.10791
MSE на шаге 9 1181.71570
MSE на шаге 10 1151.84363
MSE на шаге 11 1129.65967
MSE на шаге 12 1111.73987
MSE на шаге 13 1096.21436
MSE на шаге 14 1081.23120
MSE на шаге 15 1067.38794
MSE на шаге 16 1053.34119
MSE на шаге 17 1039.39893
MSE на шаге 18 1024.86707
MSE на шаге 19 1007.74524
MSE на шаге 20 986.26483
MSE на шаге 51 30.15092
MSE на шаге 101 9.81639
MSE на шаге 151 5.51939
MSE на шаге 201 3.27150
MSE на шаге 251 2.10506
MSE на шаге 301 1.53269
MSE на шаге 351 1.25381
MSE на шаге 401 1.12165
MSE на шаге 451 1.03756
MSE на шаге 501 0.99853
MSE на шаге 551 0.97791
MSE на шаге 601 0.96393
MSE на шаге 651 0.95182
MSE на шаге 701 0.94452
MSE на шаге 751 0.94003
MSE на шаге 801 0.93630
MSE на шаге 851 0.93302
MSE на шаге 901 0.93003
MSE на шаге 951 0.92718
